import type { DesignDna } from "../src/lib/design-dna";

export const DESIGN_DNA_BY_CODE: Record<string, DesignDna> = {
  "PET-01": dna(
    "Modern pet bakım ve veteriner vitrini",
    palette(["Warm cream", "#fff7ed"], ["Care orange", "#f97316"], ["Soft peach", "#fed7aa"], ["Deep cocoa", "#431407"], ["Fresh green", "#22c55e"]),
    "Yuvarlak hissi olan modern sans-serif başlıklar ve okunaklı servis metinleri.",
    "Sevecen hayvan fotoğrafları, bol hizmet kartı ve randevu odaklı güven akışı.",
    ["Belirgin randevu CTA'ları", "Hizmet ve paket kartları", "Yumuşak ikon kapsülleri", "Güven veren yorum alanları"],
    ["Conversion odaklı hero", "Çok bölümlü servis anlatımı", "Galeri ve ekip blokları", "FAQ ile kapanan net akış"],
    "Hafif hover vurguları ve düşük sürtünmeli randevu yönlendirmesi.",
    ["Tek kolon servis akışı", "Erken görünen iletişim CTA'sı", "Rahat dokunma alanları", "Fotoğraf ve metin dengesi"],
    ["Online randevu talebi", "Pet bakım paketleri", "Veteriner/pet oteli uyarlaması", "Öncesi-sonrası galeri"],
    ["Pet kuaförleri", "Veteriner klinikleri", "Pet bakım merkezleri", "Pet oteli işletmeleri"],
    ["Marka renkleri", "Hizmet paketleri", "Fotoğraf galerisi", "Randevu ve WhatsApp akışı", "Ekip ve yorum içerikleri"],
  ),
  "PET-02": dna(
    "Sade editoryal pet grooming",
    palette(["Ivory", "#fffaf3"], ["Terracotta", "#c86f4a"], ["Sage", "#8a9a74"], ["Charcoal", "#1f2933"], ["Sand", "#ead8bd"]),
    "Büyük editoryal başlıklar, sade açıklama metinleri ve sakin boşluk ritmi.",
    "Minimal grooming anlatımı, doğal fotoğraflar ve sakin bakım hikayesi.",
    ["Az sayıda ama güçlü CTA", "İnce çizgili kartlar", "Fotoğraf odaklı geçişler", "Sade fiyat/hizmet listeleri"],
    ["Geniş boşluklu hero", "Hizmet, süreç ve galeri sırası", "Temiz referans alanları", "Kısa FAQ kapanışı"],
    "Dikkat dağıtmayan geçişler ve editorial sayfa kaydırma hissi.",
    ["Büyük başlıkların kontrollü kırılımı", "Galeri öncelikli akış", "Kısa hizmet blokları", "Okunaklı fiyat/süre bilgileri"],
    ["Grooming hizmetleri", "Bakım süreci anlatımı", "Fiyat paketleri", "Müşteri yorumları"],
    ["Butik pet kuaförleri", "Tek lokasyonlu bakım salonları", "Fotoğraf kalitesi yüksek işletmeler", "Sade marka dili isteyen pet markaları"],
    ["Fotoğraf dili", "Hizmet kategori adları", "Paket ve fiyat tabloları", "Süreç adımları", "Renk ve ikon seti"],
  ),
  "PET-03": dna(
    "Koyu yaratıcı stüdyo tarzı pet marka uyarlaması",
    palette(["Obsidian", "#07070a"], ["Graphite", "#18181b"], ["Electric lime", "#b7ff2a"], ["Cool white", "#f8fafc"], ["Steel", "#71717a"]),
    "Kalın sans-serif başlıklar, yüksek kontrast ve ajans işi güçlü hiyerarşi.",
    "Pet sektörü için birebir değil; premium, koyu ve cesur bir marka dili referansı.",
    ["Koyu yüzeyler", "Keskin CTA blokları", "Büyük tipografik alanlar", "Portfolyo benzeri hizmet sunumu"],
    ["Ajans vitrini gibi açılış", "Proje/hizmet kartları", "Büyük görsel bloklar", "Kontrastlı kapanış CTA'sı"],
    "Enerjik hover tepkileri ve koyu tema üzerinde parlak vurgu kullanımı.",
    ["Tek kolon koyu anlatım", "Büyük ama kısa başlıklar", "Net CTA ayrımı", "Yüksek kontrast okunabilirlik"],
    ["Premium pet bakım paketleri", "Markalı görsel galeri", "Özel üyelik/bakım planları", "WhatsApp ve randevu akışı"],
    ["Premium pet salonları", "Şehirli butik pet markaları", "Daha cesur kimlik isteyen işletmeler", "Fotoğraf/video içeriği güçlü markalar"],
    ["Koyu tema yoğunluğu", "Vurgu rengi", "Pet fotoğraf seti", "Üyelik/paket kurgusu", "CTA ve iletişim dili"],
  ),
  "KUA-01": dna(
    "Modern saç salonu dönüşüm akışı",
    palette(["Porcelain", "#f8fafc"], ["Ink", "#111827"], ["Rose beige", "#e8cfc3"], ["Copper", "#b76e4c"], ["Mist", "#e5e7eb"]),
    "Modern salon hissi veren net sans-serif başlıklar ve yüksek okunurluk.",
    "Salon hizmetleri, ekip, yorum ve randevu akışı güçlü, dönüşüm odaklı yapı.",
    ["Rezervasyon CTA'sı", "Servis kartları", "Uzman ekip profilleri", "Yorum ve FAQ blokları"],
    ["Güçlü hero", "Hizmet ayrımı", "Ekip ve sosyal kanıt", "Randevuya bağlanan kapanış"],
    "Hızlı rezervasyon akışı ve yumuşak kart geçişleri.",
    ["Randevu butonu erken görünür", "Servisler tek tek taranır", "Ekip kartları sadeleşir", "Fiyat ve süre bilgileri kısa kalır"],
    ["Online randevu", "Hizmet listesi", "Uzman ekip", "Fiyat veya paket alanı"],
    ["Kadın kuaförleri", "Unisex salonlar", "Saç tasarım stüdyoları", "Çok hizmetli güzellik işletmeleri"],
    ["Salon fotoğrafları", "Hizmet kategorileri", "Uzman profilleri", "Fiyat listesi", "Rezervasyon bağlantısı"],
  ),
  "KUA-02": dna(
    "Editoryal saç ve güzellik salonu",
    palette(["Cream", "#fbf4ea"], ["Black", "#0f0f0f"], ["Taupe", "#a8917c"], ["Warm gray", "#d7cec4"], ["Soft white", "#ffffff"]),
    "Büyük editorial başlıklar, sade alt metinler ve rafine boşluk kullanımı.",
    "Sakin, ferah, seçkin görsel kullanımıyla butik salon anlatımı.",
    ["Minimal navigasyon", "İnce kenarlıklı bloklar", "Fotoğraf merkezli servis sunumu", "Sade CTA alanları"],
    ["Geniş hero boşluğu", "Servis ve ekip ritmi", "Galeri hissi", "Kısa güven/yorum blokları"],
    "Düşük hareketli, odaklı ve premium algıyı bozmayan geçişler.",
    ["Okunabilir büyük başlık kırılımları", "Fotoğraflar içerikten önce nefes alır", "Az seçenekli CTA", "Tek kolon rahat tarama"],
    ["Saç kesim ve bakım hizmetleri", "Ekip sunumu", "Salon atmosferi galerisi", "Randevu talebi"],
    ["Butik saç stüdyoları", "Minimal marka dili isteyen salonlar", "Editorial fotoğraf dili olan işletmeler", "Premium ama sakin görünmek isteyen kuaförler"],
    ["Görsel ritim", "Hizmet isimleri", "Randevu metni", "Marka tonu", "Sosyal medya galerisi"],
  ),
  "KUA-03": dna(
    "Premium koyu barber lounge",
    palette(["Near black", "#080808"], ["Gold", "#c8a45d"], ["Espresso", "#2a1c14"], ["Bone", "#f5efe6"], ["Smoke", "#4b5563"]),
    "Klasik barber hissi veren güçlü başlıklar ve lüks lounge tonu.",
    "Koyu, maskülen, altın vurgulu ve randevu odaklı berber deneyimi.",
    ["Gold CTA'lar", "Koyu servis kartları", "Atmosfer fotoğrafları", "Rezervasyon yönlendirmesi"],
    ["Tam ekran atmosfer hero", "Servis ve fiyat blokları", "Usta/profil alanları", "Konum ve randevu kapanışı"],
    "Premium algıyı destekleyen kontrollü hover ve rezervasyon yönlendirmesi.",
    ["Yüksek kontrast metin", "Servis fiyatları kısa kartlarda", "Randevu CTA'sı belirgin", "Görseller dikey ritme uyarlanır"],
    ["Berber randevusu", "Tıraş ve bakım paketleri", "Usta tanıtımı", "Salon atmosferi"],
    ["Barber shop'lar", "Erkek bakım salonları", "Premium randevulu stüdyolar", "Lounge konseptli işletmeler"],
    ["Altın/vurgu tonu", "Servis paketleri", "Usta profilleri", "Rezervasyon akışı", "Mekan fotoğrafları"],
  ),
  "GUZ-01": dna(
    "Modern spa ve wellness vitrini",
    palette(["Spa ivory", "#fbf7f0"], ["Clay rose", "#c58b7d"], ["Sage green", "#8ea58d"], ["Soft beige", "#eadfce"], ["Deep olive", "#26352b"]),
    "Zarif ama modern sans-serif başlıklar, rahat okunan wellness metinleri.",
    "Spa, paket, ekip, üyelik ve randevu akışını güven veren şekilde sunan yapı.",
    ["Bakım paket kartları", "Randevu CTA'ları", "Uzman ve yorum alanları", "Yumuşak renk geçişleri"],
    ["Hero sonrası güven göstergeleri", "Hizmet/paket bölümleri", "Ekip ve üyelik alanları", "FAQ ve iletişim kapanışı"],
    "Sakin geçişler, yumuşak hoverlar ve rezervasyon odaklı aksiyonlar.",
    ["Paketler tek kolon akar", "CTA'lar açık görünür", "Uzman kartları sadeleşir", "Fotoğraf-metni dengeli kalır"],
    ["Bakım paketleri", "Uzman profilleri", "Kampanya/üyelik alanı", "Online randevu formu"],
    ["Spa merkezleri", "Güzellik salonları", "Wellness stüdyoları", "Çok hizmetli bakım merkezleri"],
    ["Bakım kategorileri", "Paket detayları", "Kampanya alanı", "Uzman fotoğrafları", "Randevu sistemi"],
  ),
  "GUZ-02": dna(
    "Sade wellness editoryali",
    palette(["Warm white", "#fffaf5"], ["Muted mauve", "#b9938d"], ["Oat", "#e8d8c8"], ["Charcoal brown", "#2a211d"], ["Pale blush", "#f4dfd9"]),
    "Tipografi ağırlıklı, sakin ve geniş boşluklu editorial güzellik dili.",
    "Az öğeyle daha seçkin görünen, spa/wellness odaklı tek sayfa hissi.",
    ["Sade servis blokları", "İnce CTA'lar", "Nefes alan fotoğraf kullanımı", "Dingin renk yüzeyleri"],
    ["Tek sayfa akışı", "Hizmet ve süreç ayrımı", "Yorum/kanıt alanı", "Yumuşak kapanış CTA'sı"],
    "Sakin kaydırma, minimal hover ve içerik odaklı gezinme.",
    ["Metinler kısa bloklara ayrılır", "Fotoğraflar dikey akışta öne çıkar", "CTA sayısı az kalır", "Beyaz alan korunur"],
    ["Spa uygulamaları", "Bakım hizmetleri", "Paket ve süre bilgisi", "Randevu talebi"],
    ["Butik spa salonları", "Cilt bakım stüdyoları", "Minimal marka dili isteyen güzellik merkezleri", "Tek lokasyonlu wellness işletmeleri"],
    ["Ton ve renk sıcaklığı", "Hizmet metinleri", "Görsel seçimi", "Paket kurgusu", "İletişim akışı"],
  ),
  "GUZ-03": dna(
    "Koyu beauty portfolio",
    palette(["Black", "#050505"], ["Deep plum", "#3b1f32"], ["Soft rose", "#d8a0a6"], ["Champagne", "#f3e7d8"], ["Graphite", "#27272a"]),
    "Portfolyo hissi veren büyük editorial başlıklar ve dramatik kontrast.",
    "Koyu, güzellik fotoğrafı odaklı, premium ve kişisel stüdyo algısı güçlü.",
    ["Tam ekran görsel etkisi", "Koyu portfolyo kartları", "Az ama net CTA", "Güçlü görsel hiyerarşi"],
    ["Beauty hero", "Portfolyo/hizmet blokları", "Kısa profil anlatımı", "İletişim kapanışı"],
    "Görsel odaklı geçişler ve koyu tema üzerinde rafine hoverlar.",
    ["Dikey görsel alanlar", "Kısa portfolyo listeleri", "Kontrastlı butonlar", "Okunabilir koyu zemin"],
    ["Makyaj ve güzellik portfolyosu", "Randevu talebi", "Hizmet paketleri", "Öncesi-sonrası görselleri"],
    ["Makyaj stüdyoları", "Premium beauty salonları", "Kişisel uzman markaları", "Fotoğraf ağırlıklı güzellik işletmeleri"],
    ["Portfolyo kategorileri", "Koyu tema yoğunluğu", "Vurgu rengi", "Randevu metni", "Uzman/profil alanı"],
  ),
  "KLI-01": dna(
    "Modern dental klinik",
    palette(["Clinical white", "#ffffff"], ["Dental blue", "#2563eb"], ["Aqua", "#38bdf8"], ["Pale cyan", "#ecfeff"], ["Slate", "#0f172a"]),
    "Net, temiz ve güven veren modern sans-serif klinik tipografisi.",
    "Doktor, tedavi, yorum ve randevu akışıyla klasik ama güvenilir klinik sitesi.",
    ["Tedavi kartları", "Doktor profilleri", "Book Now CTA'ları", "Hasta yorum alanları"],
    ["Hero sonrası hizmetler", "Ekip ve uzmanlık anlatımı", "Sosyal kanıt", "FAQ/randevu kapanışı"],
    "Güven veren düşük riskli hareketler ve randevu yönlendirmeleri.",
    ["Tedaviler tek kolon", "Randevu CTA'sı görünür", "Doktor kartları kısa", "Medikal metinler bölünmüş"],
    ["Tedavi anlatımları", "Hekim profilleri", "Hasta yorumları", "Randevu talebi"],
    ["Diş klinikleri", "Özel poliklinikler", "Yeni açılan klinikler", "Çok hekimli sağlık işletmeleri"],
    ["Tedavi kategorileri", "Hekim bilgileri", "Klinik fotoğrafları", "Randevu akışı", "Güven belgeleri"],
  ),
  "KLI-02": dna(
    "Sade dermatoloji/klinik editoryali",
    palette(["Soft white", "#fbfbf7"], ["Sage", "#93a88b"], ["Warm gray", "#d8d2c8"], ["Charcoal", "#222222"], ["Pale mint", "#eef5ed"]),
    "Büyük, rafine başlıklar ve uzmanlık hissi veren sakin açıklama metinleri.",
    "Dermatoloji referansından alınan ferah klinik estetiği ve güven işaretleri.",
    ["Uzmanlık odaklı bloklar", "İnce CTA'lar", "Sertifika güven alanları", "Sade yorum kartları"],
    ["Editorial klinik hero", "Tedavi kategorileri", "Uzmanlık ve güven", "Randevu kapanışı"],
    "Sakin geçişler, profesyonel hoverlar ve klinik güvenini bozmayan akış.",
    ["Uzun metinler kısa parçalara ayrılır", "Güven işaretleri üstte kalır", "Tedavi listeleri okunur", "CTA kontrollü kullanılır"],
    ["Uzmanlık anlatımı", "Tedavi sayfaları", "Hasta güven işaretleri", "Randevu talebi"],
    ["Diş klinikleri", "Dermatoloji klinikleri", "Özel muayenehaneler", "Premium sağlık danışmanları"],
    ["Tedavi metinleri", "Hekim/sertifika alanları", "Renk tonu", "Hasta yorumları", "Randevu formu"],
  ),
  "KLI-03": dna(
    "Koyu butik dental klinik",
    palette(["Deep clinic", "#0d1117"], ["Warm light", "#d7b98e"], ["Charcoal", "#1f2937"], ["Ivory", "#f8f4ee"], ["Muted teal", "#5f8f8b"]),
    "Butik klinik algısı veren modern, koyu tema uyumlu yüksek kontrast tipografi.",
    "Koyu, sıcak ışıklı, premium dental deneyimi ve güven hissi.",
    ["Koyu tedavi kartları", "Premium CTA'lar", "İç mekan fotoğrafı vurgusu", "Butik güven anlatımı"],
    ["Moody hero", "Tedavi ve yaklaşım blokları", "Yorum/güven alanı", "Randevu kapanışı"],
    "Kontrollü geçişler ve koyu tema üzerinde sakin vurgu animasyonları.",
    ["Kontrast korunur", "Tedavi kartları kısa tutulur", "Randevu CTA'sı net", "Görseller dikey kırpılır"],
    ["Butik dental hizmetler", "Tedavi anlatımı", "Hekim/klinik güveni", "Randevu talebi"],
    ["Premium diş klinikleri", "Butik sağlık merkezleri", "İmplant/estetik diş odaklı klinikler", "Lüks klinik algısı isteyen markalar"],
    ["Koyu renk derinliği", "Vurgu rengi", "Tedavi paketleri", "Hekim profilleri", "Klinik fotoğrafları"],
  ),
  "RES-01": dna(
    "Modern restoran ve menü vitrini",
    palette(["Warm white", "#fffaf3"], ["Tomato", "#d94b2b"], ["Olive", "#586b3f"], ["Charcoal", "#1f2933"], ["Light wheat", "#f1dfbd"]),
    "Modern restoran şablonlarına uygun net başlıklar ve kolay taranan menü metinleri.",
    "Yemek fotoğrafı, menü, rezervasyon ve hikaye alanlarını dengeli sunan yapı.",
    ["Menü kartları", "Rezervasyon CTA'sı", "Fotoğraf odaklı bloklar", "Şube/iletişim alanları"],
    ["Hero ve menü önceliği", "Hikaye bölümü", "Galeri ve yorumlar", "Rezervasyon kapanışı"],
    "Hızlı menü taraması ve rezervasyona yönlendiren basit etkileşimler.",
    ["Menü kartları tek kolon", "Rezervasyon erken görünür", "Fotoğraflar dikey ritme uyar", "Şube bilgileri kısa kalır"],
    ["Dijital menü", "Masa rezervasyonu", "Mekan galerisi", "Şube/konum bilgisi"],
    ["Restoranlar", "Kafeler", "Bistro işletmeleri", "Menü ve rezervasyon odaklı markalar"],
    ["Menü kategorileri", "Yemek fotoğrafları", "Rezervasyon bağlantısı", "Şube bilgileri", "Kampanya alanları"],
  ),
  "RES-02": dna(
    "Sade atmosfer odaklı restoran",
    palette(["Paper", "#faf7f0"], ["Ink", "#111111"], ["Olive gray", "#7b806e"], ["Stone", "#d6cfc2"], ["Wine", "#6f2d2d"]),
    "Minimal, atmosfer odaklı başlıklar ve sakin menü açıklamaları.",
    "Gürültüsüz, imaj ve menü dengesi güçlü, modern-minimal restoran anlatımı.",
    ["Sade menü blokları", "Geniş fotoğraf alanları", "İnce çizgili ayrımlar", "Az sayıda CTA"],
    ["Atmosfer hero", "Menü ve hikaye sırası", "Galeri kullanımı", "Rezervasyon kapanışı"],
    "Düşük hareketli, içerik ve fotoğrafı öne çıkaran etkileşimler.",
    ["Menü kısa parçalar halinde", "Fotoğraf ağırlığı korunur", "CTA sayısı kontrollü", "Boşluk ritmi sade kalır"],
    ["Menü anlatımı", "Mekan hikayesi", "Galeri", "Rezervasyon/iletişim"],
    ["Butik kafeler", "Şef restoranları", "Minimal bistro markaları", "Atmosferi güçlü mekanlar"],
    ["Menü dili", "Görsel seçimi", "Rezervasyon metni", "Renk sıcaklığı", "Mekan hikayesi"],
  ),
  "RES-03": dna(
    "Koyu fine-dining restoran",
    palette(["Restaurant black", "#080605"], ["Amber", "#d99a32"], ["Burgundy", "#5b1f1f"], ["Cream", "#fff4df"], ["Dark clay", "#2a1812"]),
    "Şık restoran hissi veren büyük başlıklar ve yüksek kontrast menü tipografisi.",
    "Koyu, iştah açıcı, premium yemek fotoğrafları ve güçlü rezervasyon akışı.",
    ["Koyu menü kartları", "Sıcak CTA'lar", "Görsel menü etkileşimi", "Puan/yorum güven alanları"],
    ["Fine-dining hero", "Menü ve görsel bloklar", "Deneyim/yorum alanı", "Rezervasyon kapanışı"],
    "Görsel menüye odaklanan, premium hissi destekleyen geçişler.",
    ["Koyu kontrast korunur", "Menü kartları kısa", "Rezervasyon belirgin", "Fotoğraflar yüksek etkili kullanılır"],
    ["Dijital menü", "Masa rezervasyonu", "Yorum/puan alanı", "Mekan galerisi"],
    ["Fine-dining restoranlar", "Premium kafeler", "Bar ve lounge mekanları", "Akşam deneyimi güçlü markalar"],
    ["Menü bölümleri", "Rezervasyon sağlayıcısı", "Yemek fotoğrafları", "Koyu tema tonu", "Özel etkinlik alanları"],
  ),
  "EML-01": dna(
    "Modern emlak ajansı vitrini",
    palette(["Clean white", "#ffffff"], ["Estate blue", "#2563eb"], ["Pale blue", "#eff6ff"], ["Slate", "#172554"], ["Silver", "#e2e8f0"]),
    "Temiz ajans hissi veren modern sans-serif başlıklar ve ilan odaklı okunur metinler.",
    "Portföy, danışman ve değerleme talebini güvenli bir modern akışta sunar.",
    ["İlan kartları", "Filtre hissi veren bloklar", "Danışman profilleri", "Net CTA alanları"],
    ["Hero sonrası portföy", "Hizmet ve danışman akışı", "Güven/yorum alanları", "İletişim kapanışı"],
    "Hızlı inceleme, net CTA ve portföy keşfine uygun etkileşimler.",
    ["İlan kartları tek kolon", "Danışman bilgileri kısa", "Değerleme CTA'sı görünür", "Harita/konum alanları sadeleşir"],
    ["İlan filtreleme", "Danışman profilleri", "Portföy sunumu", "Değerleme talebi"],
    ["Emlak ofisleri", "Gayrimenkul danışmanları", "Konut proje satış ekipleri", "Portföy odaklı ajanslar"],
    ["Portföy kategorileri", "Danışman profilleri", "Değerleme formu", "Harita entegrasyonu", "İlan görselleri"],
  ),
  "EML-02": dna(
    "Lüks villa editoryali",
    palette(["Santorini white", "#fffdf8"], ["Aegean blue", "#2f6f9f"], ["Warm sand", "#e8d4b8"], ["Ink", "#171717"], ["Stone", "#c8c0b6"]),
    "Serif hissi veren editorial başlıklar ve çok sade emlak metinleri.",
    "Villa/lüks konaklama referansından gelen büyük fotoğraf, az metin ve seçkin atmosfer.",
    ["Tam genişlik mimari fotoğraflar", "Minimal CTA", "Sade özellik listeleri", "Clutter-free navigasyon"],
    ["Görsel hero", "Mülk hikayesi", "Galeri akışı", "İletişim/değerleme kapanışı"],
    "Fotoğraf ve mimari atmosferi öne çıkaran düşük hareketli deneyim.",
    ["Büyük görseller kontrollü kırpılır", "Metinler kısa kalır", "CTA sadeleşir", "Galeri dikey akar"],
    ["Portföy hikayesi", "Lüks mülk sunumu", "Danışman iletişimi", "Değerleme veya randevu talebi"],
    ["Lüks emlak danışmanları", "Villa satış ekipleri", "Butik gayrimenkul markaları", "Az sayıda seçkin portföyü olan ofisler"],
    ["Portföy görselleri", "Mülk detayları", "Danışman alanı", "Tipografik ton", "İletişim formu"],
  ),
  "EML-03": dna(
    "Koyu lüks gayrimenkul",
    palette(["Forest black", "#07110c"], ["Moss", "#536b45"], ["Gold", "#c9a15d"], ["Ivory", "#f5efe2"], ["Deep green", "#163022"]),
    "Lüks konut algısı veren büyük, sakin ve koyu tema uyumlu başlıklar.",
    "Moody mimari/doğa fotoğrafı, lüks villa hissi ve zengin portföy sunumu.",
    ["Koyu portföy kartları", "Premium CTA'lar", "Mimari fotoğraf ağırlığı", "Blog/servis blokları"],
    ["Atmosferik hero", "Properties ve servisler", "Yorum/güven akışı", "İletişim kapanışı"],
    "Premium algıyı destekleyen ölçülü hover ve görsel odaklı geçişler.",
    ["Koyu kontrast korunur", "Portföy kartları tek kolon", "CTA netleşir", "Fotoğraflar dikey vurgulanır"],
    ["Lüks portföy sunumu", "Danışmanlık hizmetleri", "Blog/içgörü alanı", "Değerleme talebi"],
    ["Lüks emlak ofisleri", "Villa ve arsa proje satış ekipleri", "Yatırım odaklı danışmanlar", "Premium gayrimenkul markaları"],
    ["Portföy kategori yapısı", "Koyu tema tonu", "Vurgu rengi", "Danışman profilleri", "Harita/değerleme akışı"],
  ),
  "OTO-01": dna(
    "Modern oto servis dönüşüm sayfası",
    palette(["Service white", "#ffffff"], ["Signal red", "#ef4444"], ["Steel blue", "#334155"], ["Light gray", "#f1f5f9"], ["Black", "#111827"]),
    "Güçlü ve pratik servis hissi veren modern sans-serif başlıklar.",
    "Oto servis, fiyat, süreç ve randevu akışını net şekilde anlatan conversion yapısı.",
    ["Servis kartları", "Fiyat/paket blokları", "Süreç adımları", "Randevu CTA'ları"],
    ["Hero sonrası hizmetler", "Paket ve süreç", "FAQ ve güven", "Randevu kapanışı"],
    "Hızlı servis randevusu ve net aksiyonlara yönlendiren pratik etkileşimler.",
    ["Servisler tek kolon", "Paketler kısa kartlarda", "Randevu CTA'sı belirgin", "Süreç adımları numaralı akar"],
    ["Servis randevusu", "Hizmet paketleri", "Araç teslim süreci", "Konum ve yol tarifi"],
    ["Oto servisleri", "Tamir bakım işletmeleri", "Lastik ve bakım merkezleri", "Çok hizmetli garajlar"],
    ["Servis listesi", "Paket fiyatları", "Randevu akışı", "Konum bilgisi", "Araç teslim süreci"],
  ),
  "OTO-02": dna(
    "Minimal stüdyo tarzı otomotiv uyarlaması",
    palette(["Studio white", "#fbfbfb"], ["Black", "#0f0f0f"], ["Concrete", "#d6d3d1"], ["Muted blue", "#62748e"], ["Silver", "#e7e5e4"]),
    "Swiss/editorial hissi olan büyük sans-serif başlıklar ve çok sade metin ritmi.",
    "Otomotiv için birebir değil; minimal, stüdyo kalitesinde marka sunumu referansı.",
    ["Az renkli yüzeyler", "Büyük tipografi", "Portfolyo benzeri iş sunumu", "İnce çizgili CTA'lar"],
    ["Minimal hero", "Seçilmiş hizmet/proje blokları", "Süreç anlatımı", "İletişim kapanışı"],
    "Sakin, ajans/stüdyo kalitesinde ve içerik odaklı geçişler.",
    ["Başlıklar kısa kırılır", "Kart sayısı sınırlı kalır", "Görseller temiz akar", "CTA gürültüsüzdür"],
    ["Premium bakım hizmetleri", "İşçilik portföyü", "Süreç ve teslim anlatımı", "Randevu talebi"],
    ["Detailing stüdyoları", "Premium oto bakım markaları", "Az hizmetli butik garajlar", "Görsel portföyü güçlü işletmeler"],
    ["Otomotiv görselleri", "Hizmet seçkisi", "Portfolyo/proje alanı", "Renk nötrlüğü", "İletişim formu"],
  ),
  "OTO-03": dna(
    "Koyu premium body shop",
    palette(["Garage black", "#08090b"], ["Racing red", "#dc2626"], ["Carbon", "#1f2937"], ["Chrome", "#d1d5db"], ["Amber", "#f59e0b"]),
    "Yüksek enerjili, koyu tema üzerinde güçlü oto servis tipografisi.",
    "Koyu, performans odaklı, body shop/detailing ve güven puanlarıyla destekli.",
    ["Koyu hizmet kartları", "Kırmızı CTA'lar", "Puan/yorum göstergeleri", "CMS servis/news alanları"],
    ["Dramatik hero", "Servis ve haber blokları", "Güven puanı", "Randevu kapanışı"],
    "Enerjik hoverlar, hızlı aksiyonlar ve performans hissi veren vurgu kullanımı.",
    ["Koyu kontrast güçlü", "Servisler kısa bloklarda", "Randevu CTA'sı sabit zihinde kalır", "Görseller agresif kırpılır"],
    ["Body shop hizmetleri", "Detailing/tuning paketleri", "Müşteri yorumları", "Servis randevusu"],
    ["Premium oto servisleri", "Detailing merkezleri", "Body shop işletmeleri", "Performans/tuning garajları"],
    ["Servis kategorileri", "Kırmızı/vurgu tonu", "Araç görselleri", "Yorum/puan alanı", "Randevu ve konum akışı"],
  ),
  "MIM-01": dna(
    "Modern renovation ve inşaat akışı",
    palette(["Builder white", "#ffffff"], ["Construction yellow", "#facc15"], ["Graphite", "#1f2937"], ["Concrete", "#e5e7eb"], ["Warm wood", "#9a6b3f"]),
    "Net, güven veren ve dönüşüm odaklı inşaat/renovasyon tipografisi.",
    "Servis, süreç, FAQ ve iletişim hunisi güçlü, açıklayıcı inşaat referansı.",
    ["Hizmet kartları", "Süreç adımları", "Güçlü CTA hunisi", "FAQ ve güven alanları"],
    ["Hero sonrası hizmetler", "Çalışma süreci", "Proje/kanıt blokları", "Contact kapanışı"],
    "Teklif veya keşif talebine yönlendiren, net ve düşük sürtünmeli etkileşimler.",
    ["Süreç adımları numaralı akar", "Hizmet kartları kısa", "Keşif CTA'sı belirgin", "Uzun içerikler bölümlenir"],
    ["Proje portföyü", "Hizmet alanları", "Süreç anlatımı", "Keşif talebi"],
    ["Renovasyon firmaları", "İnşaat şirketleri", "Tadilat ekipleri", "Proje bazlı hizmet veren firmalar"],
    ["Hizmet alanları", "Proje görselleri", "Süreç adımları", "Keşif formu", "Güven belgeleri"],
  ),
  "MIM-02": dna(
    "Sade mimarlık/interior editoryali",
    palette(["Gallery white", "#fafaf8"], ["Black", "#111111"], ["Stone", "#c9c3b8"], ["Warm gray", "#e7e2da"], ["Muted olive", "#6f735f"]),
    "Mimarlık stüdyosu hissi veren rafine, sade ve proje odaklı tipografi.",
    "Az öğeli, seçilmiş projeleri ve stüdyo tavrını öne çıkaran editorial yapı.",
    ["Büyük proje görselleri", "Minimal navigasyon", "İnce metin blokları", "Sade proje listeleri"],
    ["Project-first hero", "Stüdyo anlatımı", "Seçilmiş işler", "İletişim kapanışı"],
    "Galeri benzeri sakin geçişler ve projeyi öne çıkaran düşük hareket.",
    ["Projeler dikey galeriye dönüşür", "Metinler kısa tutulur", "Boşluk ritmi korunur", "CTA minimaldir"],
    ["Proje portföyü", "Stüdyo/hizmet anlatımı", "Referans proje detayları", "İletişim/keşif talebi"],
    ["Mimarlık ofisleri", "İç mimarlık stüdyoları", "Dekorasyon markaları", "Az ama güçlü portföyü olan ekipler"],
    ["Proje kategorileri", "Stüdyo metni", "Görsel seçimi", "Tipografik ton", "İletişim akışı"],
  ),
  "MIM-03": dna(
    "Koyu premium architecture studio",
    palette(["Studio black", "#080807"], ["Warm gold", "#c9a66b"], ["Deep brown", "#241a12"], ["Ivory", "#f7efe3"], ["Charcoal", "#27272a"]),
    "Architecture studio algısı veren büyük, sakin ve koyu tema uyumlu editorial başlıklar.",
    "Koyu, altın vurgulu, moody mimari fotoğraflar ve stüdyo metodolojisi.",
    ["Koyu proje kartları", "Altın vurgu çizgileri", "Basın/metodoloji alanları", "Premium CTA"],
    ["Moody hero", "Proje vitrini", "Stüdyo yöntemi", "Basın ve iletişim kapanışı"],
    "Premium stüdyo hissini koruyan ölçülü geçişler ve görsel odaklı hoverlar.",
    ["Koyu kontrast korunur", "Proje kartları tek kolon", "Metodoloji kısa adımlara ayrılır", "CTA net kalır"],
    ["Proje portföyü", "Metodoloji anlatımı", "Basın/referans alanı", "Keşif talebi"],
    ["Premium mimarlık ofisleri", "İç mimarlık stüdyoları", "Dekorasyon ve konsept ekipleri", "High-end inşaat markaları"],
    ["Proje görselleri", "Altın/vurgu tonu", "Metodoloji adımları", "Basın/referans alanı", "Keşif formu"],
  ),
};

function palette(...colors: Array<[name: string, value: string]>) {
  return colors.map(([name, value]) => ({
    name,
    value,
    usage: "Referans tasarım yönüne göre uyarlanabilir renk rolü",
  }));
}

function dna(
  styleName: string,
  colorPalette: DesignDna["colorPalette"],
  typographyStyle: string,
  visualDirection: string,
  uiCharacteristics: string[],
  layoutCharacteristics: string[],
  interactionStyle: string,
  mobileCharacteristics: string[],
  sectorFeatures: string[],
  suitableFor: string[],
  customizationOptions: string[],
): DesignDna {
  return {
    styleName,
    colorPalette,
    typographyStyle,
    visualDirection,
    uiCharacteristics,
    layoutCharacteristics,
    interactionStyle,
    mobileCharacteristics,
    sectorFeatures,
    suitableFor,
    customizationOptions,
  };
}
