import type { DesignColor, DesignDna } from "../src/lib/design-dna";

type Pair = [title: string, description: string];

const DECISION_DIMENSIONS = [
  "Hero kompozisyonu",
  "Navigasyon ve CTA",
  "Fotoğraf ve görsel dili",
  "Boşluk ve kart sistemi",
  "Renk ve kontrast kullanımı",
  "Mobil davranış",
] as const;

function palette(...colors: Array<[name: string, value: string]>): DesignColor[] {
  return colors.map(([name, value]) => ({
    name,
    value,
    usage: "Referans tasarım yönüne göre uyarlanabilir renk rolü",
  }));
}

function items(pairs: Pair[]) {
  return pairs.map(([title, description]) => ({ title, description }));
}

/** Six fixed analysis dimensions (same category names for every design, like
 *  GUZ-01's own "Hero kompozisyonu / Navigasyon / Fotoğraf dili / ..." list),
 *  paired with per-design descriptions passed positionally. */
function decisions(descriptions: [string, string, string, string, string, string]): Pair[] {
  return DECISION_DIMENSIONS.map((title, index) => [title, descriptions[index]]);
}

type DnaInput = {
  styleName: string;
  accent: string;
  palette: DesignColor[];
  typographyStyle: string;
  visualDirection: string;
  uiCharacteristics: string[];
  layoutCharacteristics: string[];
  interactionStyle: string;
  mobileCharacteristics: string[];
  sectorFeatures: Pair[];
  suitableFor: Pair[];
  customizationOptions: Pair[];
  keyDecisions: Pair[];
};

function dna(input: DnaInput): DesignDna {
  return {
    styleName: input.styleName,
    colorPalette: input.palette,
    typographyStyle: input.typographyStyle,
    visualDirection: input.visualDirection,
    uiCharacteristics: input.uiCharacteristics,
    layoutCharacteristics: input.layoutCharacteristics,
    interactionStyle: input.interactionStyle,
    mobileCharacteristics: input.mobileCharacteristics,
    sectorFeatures: items(input.sectorFeatures),
    suitableFor: items(input.suitableFor),
    customizationOptions: items(input.customizationOptions),
    contextualAccent: input.accent,
    keyDecisions: items(input.keyDecisions),
  };
}

export const DESIGN_DNA_BY_CODE: Record<string, DesignDna> = {
  "PET-01": dna({
    styleName: "Modern pet bakım ve veteriner vitrini",
    accent: "#EA580C",
    palette: palette(["Warm cream", "#fff7ed"], ["Care orange", "#f97316"], ["Soft peach", "#fed7aa"], ["Deep cocoa", "#431407"], ["Fresh green", "#22c55e"]),
    typographyStyle: "Yuvarlak hissi olan modern sans-serif başlıklar ve okunaklı servis metinleri.",
    visualDirection: "Sevecen hayvan fotoğrafları, bol hizmet kartı ve randevu odaklı güven akışı.",
    uiCharacteristics: ["Belirgin randevu CTA'ları", "Hizmet ve paket kartları", "Yumuşak ikon kapsülleri", "Güven veren yorum alanları"],
    layoutCharacteristics: ["Conversion odaklı hero", "Çok bölümlü servis anlatımı", "Galeri ve ekip blokları", "FAQ ile kapanan net akış"],
    interactionStyle: "Hafif hover vurguları ve düşük sürtünmeli randevu yönlendirmesi.",
    mobileCharacteristics: ["Tek kolon servis akışı", "Erken görünen iletişim CTA'sı", "Rahat dokunma alanları", "Fotoğraf ve metin dengesi"],
    sectorFeatures: [
      ["Online randevu talebi", "Ziyaretçi hizmet seçip tek adımda randevu talebi bırakır."],
      ["Pet bakım paketleri", "Yıkama, tıraş ve bakım hizmetleri karşılaştırmalı kartlarda sunulur."],
      ["Veteriner/pet oteli uyarlaması", "Aynı yapı veteriner veya pet oteli hizmetlerine göre yeniden düzenlenir."],
      ["Öncesi-sonrası galeri", "Bakım sonuçları öncesi/sonrası görsel çiftleriyle güven oluşturur."],
    ],
    suitableFor: [
      ["Pet kuaförleri", "Randevu ve bakım paketi anlatımına ihtiyaç duyan kuaför işletmeleri."],
      ["Veteriner klinikleri", "Hizmet çeşitliliğini ve güveni birlikte anlatmak isteyen klinikler."],
      ["Pet bakım merkezleri", "Çoklu hizmeti tek sayfada karar aldıracak şekilde sunmak isteyenler."],
      ["Pet oteli işletmeleri", "Konaklama ve bakımı bir arada tanıtan pet otelleri."],
    ],
    customizationOptions: [
      ["Marka renkleri", "Sıcak/soğuk renk tonu işletmenizin kimliğine göre değiştirilir."],
      ["Hizmet paketleri", "Paket sayısı ve içerikleri gerçek fiyat listenize uyarlanır."],
      ["Fotoğraf galerisi", "Kendi bakım fotoğraflarınızla öncesi/sonrası galerisi doldurulur."],
      ["Randevu ve WhatsApp akışı", "Randevu formu ve WhatsApp bağlantısı gerçek hattınıza yönlendirilir."],
      ["Ekip ve yorum içerikleri", "Ekip fotoğrafları ve müşteri yorumları sizin verilerinizle güncellenir."],
    ],
    keyDecisions: decisions([
      "Sevecen hayvan fotoğrafı ve net randevu CTA'sı ilk ekranda birlikte sunulur.",
      "Randevu bağlantısı üstte sabit kalır, ikincil menü sade tutulur.",
      "Sıcak tonlu, samimi hayvan fotoğrafları hizmet kartlarını destekler.",
      "Hizmetler eşit büyüklükte kartlarda, bol boşlukla birbirinden ayrılır.",
      "Turuncu vurgu, krem zemin üzerinde CTA'ları belirgin kılar.",
      "Kartlar tek kolona iner, randevu butonu ekranın üst kısmında kalır.",
    ]),
  }),

  "PET-02": dna({
    styleName: "Sade editoryal pet grooming",
    accent: "#B25B3E",
    palette: palette(["Ivory", "#fffaf3"], ["Terracotta", "#c86f4a"], ["Sage", "#8a9a74"], ["Charcoal", "#1f2933"], ["Sand", "#ead8bd"]),
    typographyStyle: "Büyük editoryal başlıklar, sade açıklama metinleri ve sakin boşluk ritmi.",
    visualDirection: "Minimal grooming anlatımı, doğal fotoğraflar ve sakin bakım hikayesi.",
    uiCharacteristics: ["Az sayıda ama güçlü CTA", "İnce çizgili kartlar", "Fotoğraf odaklı geçişler", "Sade fiyat/hizmet listeleri"],
    layoutCharacteristics: ["Geniş boşluklu hero", "Hizmet, süreç ve galeri sırası", "Temiz referans alanları", "Kısa FAQ kapanışı"],
    interactionStyle: "Dikkat dağıtmayan geçişler ve editorial sayfa kaydırma hissi.",
    mobileCharacteristics: ["Büyük başlıkların kontrollü kırılımı", "Galeri öncelikli akış", "Kısa hizmet blokları", "Okunaklı fiyat/süre bilgileri"],
    sectorFeatures: [
      ["Grooming hizmetleri", "Bakım hizmetleri tek satırlık sade açıklamalarla listelenir."],
      ["Bakım süreci anlatımı", "Ziyaretten teslime süreç kısa adımlarla anlatılır."],
      ["Fiyat paketleri", "Fiyat/süre bilgisi gürültüsüz, okunaklı bir tabloda sunulur."],
      ["Müşteri yorumları", "Az sayıda seçilmiş yorum güveni sade şekilde destekler."],
    ],
    suitableFor: [
      ["Butik pet kuaförleri", "Tek lokasyonda özenli hizmet veren küçük stüdyolar."],
      ["Tek lokasyonlu bakım salonları", "Sade, kişisel bir marka hissi vermek isteyen salonlar."],
      ["Fotoğraf kalitesi yüksek işletmeler", "Kaliteli fotoğrafla öne çıkmak isteyen işletmeler."],
      ["Sade marka dili isteyen pet markaları", "Gürültüsüz, editorial bir görünüm isteyen markalar."],
    ],
    customizationOptions: [
      ["Fotoğraf dili", "Doğal ışıklı kendi fotoğraflarınızla galeri yeniden kurulur."],
      ["Hizmet kategori adları", "Hizmet isimleri kendi menünüze göre güncellenir."],
      ["Paket ve fiyat tabloları", "Fiyat tablosu güncel paketlerinize göre düzenlenir."],
      ["Süreç adımları", "Randevudan teslime süreç adımları işletmenize göre yazılır."],
      ["Renk ve ikon seti", "Ton sıcaklığı ve ikon seti markanıza göre ayarlanır."],
    ],
    keyDecisions: decisions([
      "Geniş boşluklu hero, tek güçlü görsel ve kısa başlıkla açılır.",
      "Menü sade tutulur; tek bir randevu bağlantısı öne çıkar.",
      "Doğal, stüdyo dışı fotoğraflar sakin bir bakım hikayesi anlatır.",
      "İçerik geniş boşluklarla nefes alır, kartlar ince çizgilerle ayrılır.",
      "Terracotta vurgu, fildişi zemin üzerinde ölçülü şekilde kullanılır.",
      "Başlıklar kontrollü kırılır, galeri mobilde öncelikli sırada kalır.",
    ]),
  }),

  "PET-03": dna({
    styleName: "Koyu yaratıcı stüdyo tarzı pet marka uyarlaması",
    accent: "#65A30D",
    palette: palette(["Obsidian", "#07070a"], ["Graphite", "#18181b"], ["Electric lime", "#b7ff2a"], ["Cool white", "#f8fafc"], ["Steel", "#71717a"]),
    typographyStyle: "Kalın sans-serif başlıklar, yüksek kontrast ve ajans işi güçlü hiyerarşi.",
    visualDirection: "Pet sektörü için birebir değil; premium, koyu ve cesur bir marka dili referansı.",
    uiCharacteristics: ["Koyu yüzeyler", "Keskin CTA blokları", "Büyük tipografik alanlar", "Portfolyo benzeri hizmet sunumu"],
    layoutCharacteristics: ["Ajans vitrini gibi açılış", "Proje/hizmet kartları", "Büyük görsel bloklar", "Kontrastlı kapanış CTA'sı"],
    interactionStyle: "Enerjik hover tepkileri ve koyu tema üzerinde parlak vurgu kullanımı.",
    mobileCharacteristics: ["Tek kolon koyu anlatım", "Büyük ama kısa başlıklar", "Net CTA ayrımı", "Yüksek kontrast okunabilirlik"],
    sectorFeatures: [
      ["Premium pet bakım paketleri", "Üst segment paketler büyük kartlarla vitrine çıkarılır."],
      ["Markalı görsel galeri", "Stüdyo kalitesinde fotoğraflar koyu zemin üzerinde öne çıkar."],
      ["Özel üyelik/bakım planları", "Süreli üyelik ya da bakım planları ayrı bir blokta anlatılır."],
      ["WhatsApp ve randevu akışı", "Koyu tema korunarak tek adımlı randevu/WhatsApp akışı sunulur."],
    ],
    suitableFor: [
      ["Premium pet salonları", "Lüks konumlanmak isteyen üst segment salonlar."],
      ["Şehirli butik pet markaları", "Şehir merkezinde cesur bir kimlik arayan markalar."],
      ["Daha cesur kimlik isteyen işletmeler", "Standart pastel pet estetiğinden ayrışmak isteyenler."],
      ["Fotoğraf/video içeriği güçlü markalar", "Elinde güçlü görsel arşivi olan markalar."],
    ],
    customizationOptions: [
      ["Koyu tema yoğunluğu", "Zemin koyuluğu ve kontrast seviyesi markanıza göre ayarlanır."],
      ["Vurgu rengi", "Parlak vurgu rengi neon yeşil dışında da seçilebilir."],
      ["Pet fotoğraf seti", "Portfolyo görselleri kendi stüdyo çekimlerinizle değiştirilir."],
      ["Üyelik/paket kurgusu", "Paket ve üyelik yapısı gerçek tekliflerinize göre kurulur."],
      ["CTA ve iletişim dili", "Buton metinleri ve ton marka sesinize göre yazılır."],
    ],
    keyDecisions: decisions([
      "Tam ekran koyu hero, tek büyük başlıkla ajans hissi verir.",
      "Menü minimal kalır; tek keskin CTA blok halinde öne çıkar.",
      "Yüksek kontrastlı, stüdyo kalitesinde fotoğraflar portfolyo gibi sunulur.",
      "Büyük görsel bloklar arasında geniş koyu boşluklar kullanılır.",
      "Neon vurgu rengi koyu zeminde CTA'ları anında görünür kılar.",
      "Mobilde tek kolon akar, kontrast ve okunabilirlik korunur.",
    ]),
  }),

  "KUA-01": dna({
    styleName: "Modern saç salonu dönüşüm akışı",
    accent: "#9C5A3C",
    palette: palette(["Porcelain", "#f8fafc"], ["Ink", "#111827"], ["Rose beige", "#e8cfc3"], ["Copper", "#b76e4c"], ["Mist", "#e5e7eb"]),
    typographyStyle: "Modern salon hissi veren net sans-serif başlıklar ve yüksek okunurluk.",
    visualDirection: "Salon hizmetleri, ekip, yorum ve randevu akışı güçlü, dönüşüm odaklı yapı.",
    uiCharacteristics: ["Rezervasyon CTA'sı", "Servis kartları", "Uzman ekip profilleri", "Yorum ve FAQ blokları"],
    layoutCharacteristics: ["Güçlü hero", "Hizmet ayrımı", "Ekip ve sosyal kanıt", "Randevuya bağlanan kapanış"],
    interactionStyle: "Hızlı rezervasyon akışı ve yumuşak kart geçişleri.",
    mobileCharacteristics: ["Randevu butonu erken görünür", "Servisler tek tek taranır", "Ekip kartları sadeleşir", "Fiyat ve süre bilgileri kısa kalır"],
    sectorFeatures: [
      ["Online randevu", "Hizmet ve uzman seçilerek tek ekranda randevu alınır."],
      ["Hizmet listesi", "Saç kesim, boya ve bakım hizmetleri kart halinde sıralanır."],
      ["Uzman ekip", "Uzman fotoğrafları ve uzmanlık alanları kısa profillerle tanıtılır."],
      ["Fiyat veya paket alanı", "Fiyat aralıkları veya paketler tek bakışta karşılaştırılır."],
    ],
    suitableFor: [
      ["Kadın kuaförleri", "Geniş hizmet menüsünü net anlatmak isteyen salonlar."],
      ["Unisex salonlar", "Farklı müşteri segmentlerine aynı sayfada hitap eden salonlar."],
      ["Saç tasarım stüdyoları", "Uzmanlık ve stili öne çıkarmak isteyen stüdyolar."],
      ["Çok hizmetli güzellik işletmeleri", "Saç dışında ek hizmetler de sunan işletmeler."],
    ],
    customizationOptions: [
      ["Salon fotoğrafları", "Mekan ve hizmet görselleri kendi çekimlerinizle değişir."],
      ["Hizmet kategorileri", "Hizmet başlıkları gerçek menünüze göre düzenlenir."],
      ["Uzman profilleri", "Uzman sayısı ve bilgileri ekibinize göre güncellenir."],
      ["Fiyat listesi", "Fiyat listesi güncel tarifenize göre yenilenir."],
      ["Rezervasyon bağlantısı", "Randevu butonu kullandığınız sisteme yönlendirilir."],
    ],
    keyDecisions: decisions([
      "Güçlü hero görseli ve net randevu CTA'sı ilk ekranda birlikte durur.",
      "Rezervasyon bağlantısı menüde sabit kalır, ikincil linkler sadeleşir.",
      "Salon ve saç fotoğrafları yüksek çözünürlükte, güven verici sunulur.",
      "Hizmet kartları eşit hizada, kısa açıklamalarla ayrılır.",
      "Bakır tonu vurgu, porselen zemin üzerinde CTA'ları belirginleştirir.",
      "Mobilde randevu butonu üstte sabitlenir, servisler tek tek taranır.",
    ]),
  }),

  "KUA-02": dna({
    styleName: "Editoryal saç ve güzellik salonu",
    accent: "#8B7355",
    palette: palette(["Cream", "#fbf4ea"], ["Black", "#0f0f0f"], ["Taupe", "#a8917c"], ["Warm gray", "#d7cec4"], ["Soft white", "#ffffff"]),
    typographyStyle: "Büyük editorial başlıklar, sade alt metinler ve rafine boşluk kullanımı.",
    visualDirection: "Sakin, ferah, seçkin görsel kullanımıyla butik salon anlatımı.",
    uiCharacteristics: ["Minimal navigasyon", "İnce kenarlıklı bloklar", "Fotoğraf merkezli servis sunumu", "Sade CTA alanları"],
    layoutCharacteristics: ["Geniş hero boşluğu", "Servis ve ekip ritmi", "Galeri hissi", "Kısa güven/yorum blokları"],
    interactionStyle: "Düşük hareketli, odaklı ve premium algıyı bozmayan geçişler.",
    mobileCharacteristics: ["Okunabilir büyük başlık kırılımları", "Fotoğraflar içerikten önce nefes alır", "Az seçenekli CTA", "Tek kolon rahat tarama"],
    sectorFeatures: [
      ["Saç kesim ve bakım hizmetleri", "Hizmetler kısa, sade satırlarla anlatılır."],
      ["Ekip sunumu", "Ekip, portre ağırlıklı sade bir galeri ile tanıtılır."],
      ["Salon atmosferi galerisi", "Mekan fotoğrafları geniş boşluklu bir galeride sunulur."],
      ["Randevu talebi", "Tek, göze çarpmayan bir CTA ile randevu alınır."],
    ],
    suitableFor: [
      ["Butik saç stüdyoları", "Kişisel, küçük ölçekli hizmet veren stüdyolar."],
      ["Minimal marka dili isteyen salonlar", "Sade ve rafine görünmek isteyen salonlar."],
      ["Editorial fotoğraf dili olan işletmeler", "Kaliteli fotoğraf arşivine sahip işletmeler."],
      ["Premium ama sakin görünmek isteyen kuaförler", "Lüksü bağırmadan anlatmak isteyen kuaförler."],
    ],
    customizationOptions: [
      ["Görsel ritim", "Fotoğraf sıklığı ve boşluk oranı markanıza göre ayarlanır."],
      ["Hizmet isimleri", "Hizmet adları kendi menünüze göre güncellenir."],
      ["Randevu metni", "CTA metni marka tonunuza göre yeniden yazılır."],
      ["Marka tonu", "Renk ve tipografi ağırlığı kimliğinize göre ince ayarlanır."],
      ["Sosyal medya galerisi", "Galeri, Instagram içeriklerinizle senkron güncellenebilir."],
    ],
    keyDecisions: decisions([
      "Geniş hero boşluğu, tek sakin görsel ve kısa başlıkla açılır.",
      "Navigasyon minimalde tutulur, tek sade CTA öne çıkar.",
      "Fotoğraflar içerikten önce nefes alacak şekilde büyük yerleştirilir.",
      "Servis ve ekip blokları ince kenarlıklarla birbirinden ayrılır.",
      "Taupe vurgu, krem zemin üzerinde düşük kontrastla kullanılır.",
      "Mobilde başlıklar kontrollü kırılır, tek kolon rahat okunur.",
    ]),
  }),

  "KUA-03": dna({
    styleName: "Premium koyu barber lounge",
    accent: "#B08535",
    palette: palette(["Near black", "#080808"], ["Gold", "#c8a45d"], ["Espresso", "#2a1c14"], ["Bone", "#f5efe6"], ["Smoke", "#4b5563"]),
    typographyStyle: "Klasik barber hissi veren güçlü başlıklar ve lüks lounge tonu.",
    visualDirection: "Koyu, maskülen, altın vurgulu ve randevu odaklı berber deneyimi.",
    uiCharacteristics: ["Gold CTA'lar", "Koyu servis kartları", "Atmosfer fotoğrafları", "Rezervasyon yönlendirmesi"],
    layoutCharacteristics: ["Tam ekran atmosfer hero", "Servis ve fiyat blokları", "Usta/profil alanları", "Konum ve randevu kapanışı"],
    interactionStyle: "Premium algıyı destekleyen kontrollü hover ve rezervasyon yönlendirmesi.",
    mobileCharacteristics: ["Yüksek kontrast metin", "Servis fiyatları kısa kartlarda", "Randevu CTA'sı belirgin", "Görseller dikey ritme uyarlanır"],
    sectorFeatures: [
      ["Berber randevusu", "Usta ve saat seçilerek koyu temada randevu alınır."],
      ["Tıraş ve bakım paketleri", "Tıraş ve bakım paketleri altın vurgulu kartlarda sıralanır."],
      ["Usta tanıtımı", "Ustalar kısa, atmosferik portrelerle tanıtılır."],
      ["Salon atmosferi", "Mekan fotoğrafları lounge hissini destekleyecek şekilde sunulur."],
    ],
    suitableFor: [
      ["Barber shop'lar", "Maskülen, atmosferi güçlü bir kimlik arayan berberler."],
      ["Erkek bakım salonları", "Premium erkek bakım hizmeti veren salonlar."],
      ["Premium randevulu stüdyolar", "Randevu odaklı, üst segment çalışan stüdyolar."],
      ["Lounge konseptli işletmeler", "Bekleme alanını da deneyimin parçası sayan işletmeler."],
    ],
    customizationOptions: [
      ["Altın/vurgu tonu", "Vurgu rengi altın dışında farklı bir tonla değiştirilebilir."],
      ["Servis paketleri", "Paket içerikleri ve fiyatları gerçek listenize uyarlanır."],
      ["Usta profilleri", "Usta sayısı ve tanıtım metinleri ekibinize göre yazılır."],
      ["Rezervasyon akışı", "Randevu adımları kullandığınız sisteme göre bağlanır."],
      ["Mekan fotoğrafları", "Atmosfer fotoğrafları kendi salon çekimlerinizle değişir."],
    ],
    keyDecisions: decisions([
      "Tam ekran atmosfer hero, koyu zeminde tek güçlü başlıkla açılır.",
      "Gold CTA sabit kalır, menü sade ve lüks bir tonda durur.",
      "Atmosfer fotoğrafları düşük anahtarlı ışıkla lounge hissini destekler.",
      "Servis ve fiyat blokları koyu kartlarda net şekilde ayrılır.",
      "Altın vurgu, neredeyse siyah zemin üzerinde kontrollü kullanılır.",
      "Mobilde yüksek kontrast korunur, randevu CTA'sı hep görünür kalır.",
    ]),
  }),

  "GUZ-01": dna({
    styleName: "Modern spa ve wellness vitrini",
    accent: "#B06E5D",
    palette: palette(["Spa ivory", "#fbf7f0"], ["Clay rose", "#c58b7d"], ["Sage green", "#8ea58d"], ["Soft beige", "#eadfce"], ["Deep olive", "#26352b"]),
    typographyStyle: "Zarif ama modern sans-serif başlıklar, rahat okunan wellness metinleri.",
    visualDirection: "Spa, paket, ekip, üyelik ve randevu akışını güven veren şekilde sunan yapı.",
    uiCharacteristics: ["Bakım paket kartları", "Randevu CTA'ları", "Uzman ve yorum alanları", "Yumuşak renk geçişleri"],
    layoutCharacteristics: ["Hero sonrası güven göstergeleri", "Hizmet/paket bölümleri", "Ekip ve üyelik alanları", "FAQ ve iletişim kapanışı"],
    interactionStyle: "Sakin geçişler, yumuşak hoverlar ve rezervasyon odaklı aksiyonlar.",
    mobileCharacteristics: ["Paketler tek kolon akar", "CTA'lar açık görünür", "Uzman kartları sadeleşir", "Fotoğraf-metni dengeli kalır"],
    sectorFeatures: [
      ["Bakım paketleri", "Cilt/spa paketleri karşılaştırmalı kartlarda sıralanır."],
      ["Uzman profilleri", "Uzmanlar kısa biyografi ve uzmanlık alanıyla tanıtılır."],
      ["Kampanya/üyelik alanı", "Süreli kampanya veya üyelik ayrı bir vurgulu blokta durur."],
      ["Online randevu formu", "Hizmet ve uzman seçilerek tek ekranda randevu alınır."],
    ],
    suitableFor: [
      ["Spa merkezleri", "Geniş hizmet menüsünü güven verici şekilde anlatmak isteyen merkezler."],
      ["Güzellik salonları", "Paket ve kampanyalarını öne çıkarmak isteyen salonlar."],
      ["Wellness stüdyoları", "Sakin, iyileştirici bir marka hissi arayan stüdyolar."],
      ["Çok hizmetli bakım merkezleri", "Farklı hizmetleri tek çatı altında sunan merkezler."],
    ],
    customizationOptions: [
      ["Bakım kategorileri", "Hizmet kategorileri gerçek menünüze göre yeniden kurulur."],
      ["Paket detayları", "Paket içerikleri ve fiyatları güncel tarifenize göre değişir."],
      ["Kampanya alanı", "Kampanya bloğu güncel fırsatlarınıza göre değiştirilir."],
      ["Uzman fotoğrafları", "Ekip görselleri kendi stüdyo çekimlerinizle güncellenir."],
      ["Randevu sistemi", "Randevu formu kullandığınız rezervasyon sistemine bağlanır."],
    ],
    keyDecisions: decisions([
      "Sakin bir hero görseli ve net randevu CTA'sı birlikte açılır.",
      "Randevu bağlantısı üstte sabit kalır, menü sade tutulur.",
      "Yumuşak, sıcak tonlu fotoğraflar güven veren bir hava kurar.",
      "Paketler eşit büyüklükte kartlarda, geniş boşluklarla ayrılır.",
      "Kil pembesi vurgu, fildişi zemin üzerinde ölçülü kullanılır.",
      "Mobilde paketler tek kolona iner, CTA'lar hep görünür kalır.",
    ]),
  }),

  "GUZ-02": dna({
    styleName: "Sade wellness editoryali",
    accent: "#A67A72",
    palette: palette(["Warm white", "#fffaf5"], ["Muted mauve", "#b9938d"], ["Oat", "#e8d8c8"], ["Charcoal brown", "#2a211d"], ["Pale blush", "#f4dfd9"]),
    typographyStyle: "Tipografi ağırlıklı, sakin ve geniş boşluklu editorial güzellik dili.",
    visualDirection: "Az öğeyle daha seçkin görünen, spa/wellness odaklı tek sayfa hissi.",
    uiCharacteristics: ["Sade servis blokları", "İnce CTA'lar", "Nefes alan fotoğraf kullanımı", "Dingin renk yüzeyleri"],
    layoutCharacteristics: ["Tek sayfa akışı", "Hizmet ve süreç ayrımı", "Yorum/kanıt alanı", "Yumuşak kapanış CTA'sı"],
    interactionStyle: "Sakin kaydırma, minimal hover ve içerik odaklı gezinme.",
    mobileCharacteristics: ["Metinler kısa bloklara ayrılır", "Fotoğraflar dikey akışta öne çıkar", "CTA sayısı az kalır", "Beyaz alan korunur"],
    sectorFeatures: [
      ["Spa uygulamaları", "Uygulamalar kısa, sade satırlarla tanıtılır."],
      ["Bakım hizmetleri", "Hizmetler tek sayfa akışında sırayla anlatılır."],
      ["Paket ve süre bilgisi", "Süre ve fiyat bilgisi sade bir listede sunulur."],
      ["Randevu talebi", "Tek, göze çarpmayan bir CTA ile randevu talebi alınır."],
    ],
    suitableFor: [
      ["Butik spa salonları", "Küçük ölçekli, kişisel hizmet veren spa salonları."],
      ["Cilt bakım stüdyoları", "Uzmanlığı sade bir dille anlatmak isteyen stüdyolar."],
      ["Minimal marka dili isteyen güzellik merkezleri", "Sadeliği önemseyen güzellik merkezleri."],
      ["Tek lokasyonlu wellness işletmeleri", "Tek şubeli, kişisel bir marka hissi verenler."],
    ],
    customizationOptions: [
      ["Ton ve renk sıcaklığı", "Renk sıcaklığı markanıza göre ince ayarlanır."],
      ["Hizmet metinleri", "Hizmet açıklamaları kendi tarifenize göre yeniden yazılır."],
      ["Görsel seçimi", "Fotoğraflar kendi mekan/uygulama görselleriniz olur."],
      ["Paket kurgusu", "Paket sayısı ve süresi güncel tarifenize göre kurulur."],
      ["İletişim akışı", "Randevu/iletişim adımı kullandığınız kanala bağlanır."],
    ],
    keyDecisions: decisions([
      "Tek sayfa akışı, az öğeyle seçkin bir açılış sunar.",
      "Navigasyon neredeyse yok denecek kadar sade, tek CTA öne çıkar.",
      "Fotoğraflar içerikten önce geniş boşlukta nefes alır.",
      "Hizmet ve süreç blokları ince ayrımlarla birbirinden ayrılır.",
      "Mauve vurgu, sıcak beyaz zemin üzerinde çok düşük kontrastla durur.",
      "Mobilde metinler kısa bloklara bölünür, beyaz alan korunur.",
    ]),
  }),

  "GUZ-03": dna({
    styleName: "Koyu beauty portfolio",
    accent: "#B4677A",
    palette: palette(["Black", "#050505"], ["Deep plum", "#3b1f32"], ["Soft rose", "#d8a0a6"], ["Champagne", "#f3e7d8"], ["Graphite", "#27272a"]),
    typographyStyle: "Portfolyo hissi veren büyük editorial başlıklar ve dramatik kontrast.",
    visualDirection: "Koyu, güzellik fotoğrafı odaklı, premium ve kişisel stüdyo algısı güçlü.",
    uiCharacteristics: ["Tam ekran görsel etkisi", "Koyu portfolyo kartları", "Az ama net CTA", "Güçlü görsel hiyerarşi"],
    layoutCharacteristics: ["Beauty hero", "Portfolyo/hizmet blokları", "Kısa profil anlatımı", "İletişim kapanışı"],
    interactionStyle: "Görsel odaklı geçişler ve koyu tema üzerinde rafine hoverlar.",
    mobileCharacteristics: ["Dikey görsel alanlar", "Kısa portfolyo listeleri", "Kontrastlı butonlar", "Okunabilir koyu zemin"],
    sectorFeatures: [
      ["Makyaj ve güzellik portfolyosu", "Çalışmalar büyük, tam ekran görsellerle vitrine çıkarılır."],
      ["Randevu talebi", "Tek net CTA ile koyu temada randevu talebi alınır."],
      ["Hizmet paketleri", "Paketler kısa, kontrastlı kartlarla sunulur."],
      ["Öncesi-sonrası görselleri", "Dönüşüm görselleri yan yana karşılaştırmalı gösterilir."],
    ],
    suitableFor: [
      ["Makyaj stüdyoları", "Portfolyosunu ön planda tutmak isteyen makyaj stüdyoları."],
      ["Premium beauty salonları", "Üst segment, görsel ağırlıklı konumlanan salonlar."],
      ["Kişisel uzman markaları", "Tek uzmanın kişisel markasını öne çıkaranlar."],
      ["Fotoğraf ağırlıklı güzellik işletmeleri", "Güçlü görsel arşivi olan güzellik işletmeleri."],
    ],
    customizationOptions: [
      ["Portfolyo kategorileri", "Portfolyo, kendi çalışma kategorilerinize göre yeniden kurulur."],
      ["Koyu tema yoğunluğu", "Zemin koyuluğu ve kontrast markanıza göre ayarlanır."],
      ["Vurgu rengi", "Vurgu rengi gül tonu dışında da seçilebilir."],
      ["Randevu metni", "CTA metni marka sesinize göre yeniden yazılır."],
      ["Uzman/profil alanı", "Profil metni ve fotoğrafı kendi bilgilerinizle güncellenir."],
    ],
    keyDecisions: decisions([
      "Tam ekran koyu hero, tek çarpıcı görselle portfolyo hissi verir.",
      "Menü minimalde kalır, tek net CTA dikkat dağıtmadan durur.",
      "Yüksek çözünürlüklü portfolyo görselleri dramatik kontrastla sunulur.",
      "Portfolyo blokları arasında geniş koyu boşluklar kullanılır.",
      "Gül tonu vurgu, neredeyse siyah zeminde seçici kullanılır.",
      "Mobilde görseller dikey akar, kontrastlı butonlar hep okunur kalır.",
    ]),
  }),

  "KLI-01": dna({
    styleName: "Modern dental klinik",
    accent: "#2563EB",
    palette: palette(["Clinical white", "#ffffff"], ["Dental blue", "#2563eb"], ["Aqua", "#38bdf8"], ["Pale cyan", "#ecfeff"], ["Slate", "#0f172a"]),
    typographyStyle: "Net, temiz ve güven veren modern sans-serif klinik tipografisi.",
    visualDirection: "Doktor, tedavi, yorum ve randevu akışıyla klasik ama güvenilir klinik sitesi.",
    uiCharacteristics: ["Tedavi kartları", "Doktor profilleri", "Book Now CTA'ları", "Hasta yorum alanları"],
    layoutCharacteristics: ["Hero sonrası hizmetler", "Ekip ve uzmanlık anlatımı", "Sosyal kanıt", "FAQ/randevu kapanışı"],
    interactionStyle: "Güven veren düşük riskli hareketler ve randevu yönlendirmeleri.",
    mobileCharacteristics: ["Tedaviler tek kolon", "Randevu CTA'sı görünür", "Doktor kartları kısa", "Medikal metinler bölünmüş"],
    sectorFeatures: [
      ["Tedavi anlatımları", "Tedaviler kısa, anlaşılır açıklamalarla kart halinde sunulur."],
      ["Hekim profilleri", "Hekimler uzmanlık alanı ve unvanla tanıtılır."],
      ["Hasta yorumları", "Seçilmiş hasta yorumları güven bölümünde sıralanır."],
      ["Randevu talebi", "Tedavi seçilerek tek ekranda randevu talebi bırakılır."],
    ],
    suitableFor: [
      ["Diş klinikleri", "Tedavi çeşitliliğini net anlatmak isteyen klinikler."],
      ["Özel poliklinikler", "Birden fazla branşı bir arada sunan poliklinikler."],
      ["Yeni açılan klinikler", "Güveni hızlıca kurmak isteyen yeni klinikler."],
      ["Çok hekimli sağlık işletmeleri", "Birden fazla hekimi tanıtması gereken işletmeler."],
    ],
    customizationOptions: [
      ["Tedavi kategorileri", "Tedavi listesi klinik hizmetlerinize göre yeniden kurulur."],
      ["Hekim bilgileri", "Hekim sayısı ve unvanları ekibinize göre güncellenir."],
      ["Klinik fotoğrafları", "Klinik içi görseller kendi çekimlerinizle değişir."],
      ["Randevu akışı", "Randevu formu kullandığınız sisteme bağlanır."],
      ["Güven belgeleri", "Sertifika/diploma alanı belgelerinize göre doldurulur."],
    ],
    keyDecisions: decisions([
      "Temiz bir hero görseli ve net randevu CTA'sı ilk ekranda durur.",
      "Randevu bağlantısı menüde sabit kalır, ikincil linkler sadeleşir.",
      "Klinik ve hekim fotoğrafları güven verici, aydınlık tonda sunulur.",
      "Tedavi kartları eşit hizada, kısa açıklamalarla ayrılır.",
      "Klinik mavisi vurgu, beyaz zemin üzerinde net kullanılır.",
      "Mobilde tedaviler tek kolona iner, randevu CTA'sı hep görünür.",
    ]),
  }),

  "KLI-02": dna({
    styleName: "Sade dermatoloji/klinik editoryali",
    accent: "#6B8F63",
    palette: palette(["Soft white", "#fbfbf7"], ["Sage", "#93a88b"], ["Warm gray", "#d8d2c8"], ["Charcoal", "#222222"], ["Pale mint", "#eef5ed"]),
    typographyStyle: "Büyük, rafine başlıklar ve uzmanlık hissi veren sakin açıklama metinleri.",
    visualDirection: "Dermatoloji referansından alınan ferah klinik estetiği ve güven işaretleri.",
    uiCharacteristics: ["Uzmanlık odaklı bloklar", "İnce CTA'lar", "Sertifika güven alanları", "Sade yorum kartları"],
    layoutCharacteristics: ["Editorial klinik hero", "Tedavi kategorileri", "Uzmanlık ve güven", "Randevu kapanışı"],
    interactionStyle: "Sakin geçişler, profesyonel hoverlar ve klinik güvenini bozmayan akış.",
    mobileCharacteristics: ["Uzun metinler kısa parçalara ayrılır", "Güven işaretleri üstte kalır", "Tedavi listeleri okunur", "CTA kontrollü kullanılır"],
    sectorFeatures: [
      ["Uzmanlık anlatımı", "Uzmanlık alanları sakin, kısa paragraflarla anlatılır."],
      ["Tedavi sayfaları", "Her tedavi kendi kısa açıklama bloğunda sunulur."],
      ["Hasta güven işaretleri", "Sertifika ve unvanlar üst bölümde görünür kalır."],
      ["Randevu talebi", "Tek, sade bir CTA ile randevu talebi alınır."],
    ],
    suitableFor: [
      ["Diş klinikleri", "Sakin, editorial bir klinik anlatımı isteyenler."],
      ["Dermatoloji klinikleri", "Uzmanlığı ferah bir dille anlatmak isteyen klinikler."],
      ["Özel muayenehaneler", "Kişisel, güven odaklı çalışan muayenehaneler."],
      ["Premium sağlık danışmanları", "Sakin ve seçkin bir görünüm isteyen danışmanlar."],
    ],
    customizationOptions: [
      ["Tedavi metinleri", "Tedavi açıklamaları kendi uzmanlık alanınıza göre yazılır."],
      ["Hekim/sertifika alanları", "Sertifika ve unvan bilgileri güncel belgelerinize göre değişir."],
      ["Renk tonu", "Yeşil vurgu farklı sakin bir tonla değiştirilebilir."],
      ["Hasta yorumları", "Yorum bölümü kendi hasta geri bildirimlerinizle doldurulur."],
      ["Randevu formu", "Randevu formu kullandığınız sisteme bağlanır."],
    ],
    keyDecisions: decisions([
      "Editorial bir hero, sakin bir görsel ve kısa başlıkla açılır.",
      "Navigasyon sade tutulur, tek ince CTA öne çıkar.",
      "Klinik fotoğrafları ferah, doğal ışıklı bir tonda sunulur.",
      "Uzmanlık ve tedavi blokları geniş boşluklarla ayrılır.",
      "Adaçayı yeşili vurgu, yumuşak beyaz zeminde düşük kontrastla durur.",
      "Mobilde uzun metinler kısa parçalara bölünür, güven işaretleri üstte kalır.",
    ]),
  }),

  "KLI-03": dna({
    styleName: "Koyu butik dental klinik",
    accent: "#B08D5A",
    palette: palette(["Deep clinic", "#0d1117"], ["Warm light", "#d7b98e"], ["Charcoal", "#1f2937"], ["Ivory", "#f8f4ee"], ["Muted teal", "#5f8f8b"]),
    typographyStyle: "Butik klinik algısı veren modern, koyu tema uyumlu yüksek kontrast tipografi.",
    visualDirection: "Koyu, sıcak ışıklı, premium dental deneyimi ve güven hissi.",
    uiCharacteristics: ["Koyu tedavi kartları", "Premium CTA'lar", "İç mekan fotoğrafı vurgusu", "Butik güven anlatımı"],
    layoutCharacteristics: ["Moody hero", "Tedavi ve yaklaşım blokları", "Yorum/güven alanı", "Randevu kapanışı"],
    interactionStyle: "Kontrollü geçişler ve koyu tema üzerinde sakin vurgu animasyonları.",
    mobileCharacteristics: ["Kontrast korunur", "Tedavi kartları kısa tutulur", "Randevu CTA'sı net", "Görseller dikey kırpılır"],
    sectorFeatures: [
      ["Butik dental hizmetler", "Tedaviler koyu, premium kartlarla sunulur."],
      ["Tedavi anlatımı", "Yaklaşım ve süreç kısa, sakin metinlerle anlatılır."],
      ["Hekim/klinik güveni", "Klinik iç mekanı ve hekim güveni ön planda tutulur."],
      ["Randevu talebi", "Tek net CTA ile koyu temada randevu alınır."],
    ],
    suitableFor: [
      ["Premium diş klinikleri", "Üst segment, butik bir kimlik arayan klinikler."],
      ["Butik sağlık merkezleri", "Sıcak ve kişisel bir deneyim sunan merkezler."],
      ["İmplant/estetik diş odaklı klinikler", "Estetik diş hizmetlerini öne çıkaran klinikler."],
      ["Lüks klinik algısı isteyen markalar", "Standart klinik estetiğinden ayrışmak isteyenler."],
    ],
    customizationOptions: [
      ["Koyu renk derinliği", "Zemin koyuluğu ve sıcaklığı markanıza göre ayarlanır."],
      ["Vurgu rengi", "Sıcak vurgu tonu farklı bir renkle değiştirilebilir."],
      ["Tedavi paketleri", "Tedavi paketleri güncel listenize göre yeniden kurulur."],
      ["Hekim profilleri", "Hekim bilgileri ve fotoğrafları ekibinize göre güncellenir."],
      ["Klinik fotoğrafları", "İç mekan görselleri kendi çekimlerinizle değişir."],
    ],
    keyDecisions: decisions([
      "Moody, sıcak ışıklı bir hero koyu zeminde açılır.",
      "Menü sade kalır, premium CTA koyu temada net görünür.",
      "İç mekan fotoğrafları sıcak ışıkla butik hissi kurar.",
      "Tedavi ve yaklaşım blokları koyu kartlarla ayrılır.",
      "Sıcak altın vurgu, koyu klinik zeminde ölçülü kullanılır.",
      "Mobilde kontrast korunur, randevu CTA'sı her zaman net kalır.",
    ]),
  }),

  "RES-01": dna({
    styleName: "Modern restoran ve menü vitrini",
    accent: "#C2410C",
    palette: palette(["Warm white", "#fffaf3"], ["Tomato", "#d94b2b"], ["Olive", "#586b3f"], ["Charcoal", "#1f2933"], ["Light wheat", "#f1dfbd"]),
    typographyStyle: "Modern restoran şablonlarına uygun net başlıklar ve kolay taranan menü metinleri.",
    visualDirection: "Yemek fotoğrafı, menü, rezervasyon ve hikaye alanlarını dengeli sunan yapı.",
    uiCharacteristics: ["Menü kartları", "Rezervasyon CTA'sı", "Fotoğraf odaklı bloklar", "Şube/iletişim alanları"],
    layoutCharacteristics: ["Hero ve menü önceliği", "Hikaye bölümü", "Galeri ve yorumlar", "Rezervasyon kapanışı"],
    interactionStyle: "Hızlı menü taraması ve rezervasyona yönlendiren basit etkileşimler.",
    mobileCharacteristics: ["Menü kartları tek kolon", "Rezervasyon erken görünür", "Fotoğraflar dikey ritme uyar", "Şube bilgileri kısa kalır"],
    sectorFeatures: [
      ["Dijital menü", "Menü kategorilere ayrılmış, taranabilir kartlarla sunulur."],
      ["Masa rezervasyonu", "Tarih ve kişi sayısı seçilerek tek adımda rezervasyon yapılır."],
      ["Mekan galerisi", "Mekan ve yemek fotoğrafları galeri bölümünde sıralanır."],
      ["Şube/konum bilgisi", "Şube adresleri ve harita konumu iletişim bölümünde durur."],
    ],
    suitableFor: [
      ["Restoranlar", "Menü ve rezervasyonu birlikte anlatmak isteyen restoranlar."],
      ["Kafeler", "Ürün çeşitliliğini görsel ağırlıklı anlatmak isteyen kafeler."],
      ["Bistro işletmeleri", "Sıcak, davetkar bir marka hissi arayan bistrolar."],
      ["Menü ve rezervasyon odaklı markalar", "Dönüşümü menü ve rezervasyona bağlayan markalar."],
    ],
    customizationOptions: [
      ["Menü kategorileri", "Menü başlıkları ve ürünler kendi listenize göre kurulur."],
      ["Yemek fotoğrafları", "Ürün fotoğrafları kendi çekimlerinizle değiştirilir."],
      ["Rezervasyon bağlantısı", "Rezervasyon formu kullandığınız sisteme bağlanır."],
      ["Şube bilgileri", "Şube sayısı ve adresleri gerçek konumlarınıza göre güncellenir."],
      ["Kampanya alanları", "Kampanya bloğu güncel fırsatlarınıza göre değiştirilir."],
    ],
    keyDecisions: decisions([
      "Hero, iştah açıcı bir yemek görseli ve net rezervasyon CTA'sıyla açılır.",
      "Menü bağlantısı üstte sabit kalır, rezervasyon her zaman erişilebilir.",
      "Yemek fotoğrafları sıcak tonlarla, iştah açıcı şekilde sunulur.",
      "Menü kartları eşit hizada, kategoriler net ayrılır.",
      "Domates kırmızısı vurgu, sıcak beyaz zeminde CTA'ları öne çıkarır.",
      "Mobilde menü tek kolona iner, rezervasyon erken görünür kalır.",
    ]),
  }),

  "RES-02": dna({
    styleName: "Sade atmosfer odaklı restoran",
    accent: "#7A2E2E",
    palette: palette(["Paper", "#faf7f0"], ["Ink", "#111111"], ["Olive gray", "#7b806e"], ["Stone", "#d6cfc2"], ["Wine", "#6f2d2d"]),
    typographyStyle: "Minimal, atmosfer odaklı başlıklar ve sakin menü açıklamaları.",
    visualDirection: "Gürültüsüz, imaj ve menü dengesi güçlü, modern-minimal restoran anlatımı.",
    uiCharacteristics: ["Sade menü blokları", "Geniş fotoğraf alanları", "İnce çizgili ayrımlar", "Az sayıda CTA"],
    layoutCharacteristics: ["Atmosfer hero", "Menü ve hikaye sırası", "Galeri kullanımı", "Rezervasyon kapanışı"],
    interactionStyle: "Düşük hareketli, içerik ve fotoğrafı öne çıkaran etkileşimler.",
    mobileCharacteristics: ["Menü kısa parçalar halinde", "Fotoğraf ağırlığı korunur", "CTA sayısı kontrollü", "Boşluk ritmi sade kalır"],
    sectorFeatures: [
      ["Menü anlatımı", "Menü kısa, editorial satırlarla anlatılır."],
      ["Mekan hikayesi", "Mekanın hikayesi kısa bir bölümde sade anlatılır."],
      ["Galeri", "Atmosfer fotoğrafları geniş, nefes alan bir galeride sunulur."],
      ["Rezervasyon/iletişim", "Tek sade bir CTA ile rezervasyon veya iletişim sağlanır."],
    ],
    suitableFor: [
      ["Butik kafeler", "Küçük, atmosferi güçlü kafeler."],
      ["Şef restoranları", "Şefin imzasını öne çıkarmak isteyen restoranlar."],
      ["Minimal bistro markaları", "Sade, gürültüsüz bir marka dili isteyen bistrolar."],
      ["Atmosferi güçlü mekanlar", "Fotoğrafla atmosfer anlatmayı önceliklendiren mekanlar."],
    ],
    customizationOptions: [
      ["Menü dili", "Menü açıklamaları kendi üslubunuza göre yeniden yazılır."],
      ["Görsel seçimi", "Fotoğraflar kendi mekan ve yemek çekimlerinizle değişir."],
      ["Rezervasyon metni", "CTA metni marka tonunuza göre güncellenir."],
      ["Renk sıcaklığı", "Zemin ve vurgu sıcaklığı markanıza göre ayarlanır."],
      ["Mekan hikayesi", "Hikaye metni kendi kuruluş öykünüzle değiştirilir."],
    ],
    keyDecisions: decisions([
      "Atmosfer hero, tek geniş fotoğraf ve kısa başlıkla açılır.",
      "Navigasyon minimalde tutulur, tek sade CTA öne çıkar.",
      "Fotoğraflar geniş alanlarda, içerikten önce nefes alır.",
      "Menü ve hikaye blokları ince çizgilerle birbirinden ayrılır.",
      "Şarap kırmızısı vurgu, kağıt tonu zeminde düşük yoğunlukla durur.",
      "Mobilde menü kısa parçalara bölünür, fotoğraf ağırlığı korunur.",
    ]),
  }),

  "RES-03": dna({
    styleName: "Koyu fine-dining restoran",
    accent: "#C17D1E",
    palette: palette(["Restaurant black", "#080605"], ["Amber", "#d99a32"], ["Burgundy", "#5b1f1f"], ["Cream", "#fff4df"], ["Dark clay", "#2a1812"]),
    typographyStyle: "Şık restoran hissi veren büyük başlıklar ve yüksek kontrast menü tipografisi.",
    visualDirection: "Koyu, iştah açıcı, premium yemek fotoğrafları ve güçlü rezervasyon akışı.",
    uiCharacteristics: ["Koyu menü kartları", "Sıcak CTA'lar", "Görsel menü etkileşimi", "Puan/yorum güven alanları"],
    layoutCharacteristics: ["Fine-dining hero", "Menü ve görsel bloklar", "Deneyim/yorum alanı", "Rezervasyon kapanışı"],
    interactionStyle: "Görsel menüye odaklanan, premium hissi destekleyen geçişler.",
    mobileCharacteristics: ["Koyu kontrast korunur", "Menü kartları kısa", "Rezervasyon belirgin", "Fotoğraflar yüksek etkili kullanılır"],
    sectorFeatures: [
      ["Dijital menü", "Menü koyu zeminde yüksek etkili görsellerle sunulur."],
      ["Masa rezervasyonu", "Tarih ve kişi sayısı seçilerek premium bir akışta rezervasyon yapılır."],
      ["Yorum/puan alanı", "Deneyim puanları ve yorumlar güven bölümünde sıralanır."],
      ["Mekan galerisi", "Mekan fotoğrafları atmosferi vurgulayan bir galeride sunulur."],
    ],
    suitableFor: [
      ["Fine-dining restoranlar", "Premium bir yemek deneyimi sunan restoranlar."],
      ["Premium kafeler", "Üst segment konumlanan kafeler."],
      ["Bar ve lounge mekanları", "Akşam atmosferini öne çıkaran mekanlar."],
      ["Akşam deneyimi güçlü markalar", "Deneyimi menüden daha önce anlatmak isteyen markalar."],
    ],
    customizationOptions: [
      ["Menü bölümleri", "Menü kategorileri gerçek listenize göre yeniden kurulur."],
      ["Rezervasyon sağlayıcısı", "Rezervasyon formu kullandığınız sisteme bağlanır."],
      ["Yemek fotoğrafları", "Ürün fotoğrafları kendi çekimlerinizle değiştirilir."],
      ["Koyu tema tonu", "Zemin koyuluğu ve sıcaklığı markanıza göre ayarlanır."],
      ["Özel etkinlik alanları", "Özel etkinlik/organizasyon bilgisi ayrı bir blokta anlatılır."],
    ],
    keyDecisions: decisions([
      "Koyu, iştah açıcı bir hero görseliyle fine-dining hissi kurulur.",
      "Rezervasyon CTA'sı sıcak tonla koyu menüde net görünür.",
      "Yemek fotoğrafları yüksek etkili, premium bir sunumla kullanılır.",
      "Menü ve görsel bloklar koyu kartlarla net ayrılır.",
      "Amber vurgu, neredeyse siyah zeminde seçici ve etkili kullanılır.",
      "Mobilde koyu kontrast korunur, rezervasyon CTA'sı belirgin kalır.",
    ]),
  }),

  "EML-01": dna({
    styleName: "Modern emlak ajansı vitrini",
    accent: "#2563EB",
    palette: palette(["Clean white", "#ffffff"], ["Estate blue", "#2563eb"], ["Pale blue", "#eff6ff"], ["Slate", "#172554"], ["Silver", "#e2e8f0"]),
    typographyStyle: "Temiz ajans hissi veren modern sans-serif başlıklar ve ilan odaklı okunur metinler.",
    visualDirection: "Portföy, danışman ve değerleme talebini güvenli bir modern akışta sunar.",
    uiCharacteristics: ["İlan kartları", "Filtre hissi veren bloklar", "Danışman profilleri", "Net CTA alanları"],
    layoutCharacteristics: ["Hero sonrası portföy", "Hizmet ve danışman akışı", "Güven/yorum alanları", "İletişim kapanışı"],
    interactionStyle: "Hızlı inceleme, net CTA ve portföy keşfine uygun etkileşimler.",
    mobileCharacteristics: ["İlan kartları tek kolon", "Danışman bilgileri kısa", "Değerleme CTA'sı görünür", "Harita/konum alanları sadeleşir"],
    sectorFeatures: [
      ["İlan filtreleme", "İlanlar tip ve konuma göre filtrelenebilir kartlarda sunulur."],
      ["Danışman profilleri", "Danışmanlar uzmanlık bölgesiyle birlikte tanıtılır."],
      ["Portföy sunumu", "Portföy öne çıkan ilanlarla vitrine taşınır."],
      ["Değerleme talebi", "Mülk bilgisi girilerek tek adımda değerleme talebi alınır."],
    ],
    suitableFor: [
      ["Emlak ofisleri", "Portföyünü düzenli bir vitrinde sunmak isteyen ofisler."],
      ["Gayrimenkul danışmanları", "Kişisel danışmanlık hizmetini öne çıkaranlar."],
      ["Konut proje satış ekipleri", "Proje bazlı satış yürüten ekipler."],
      ["Portföy odaklı ajanslar", "İlan sayısı yüksek, düzenli sunum isteyen ajanslar."],
    ],
    customizationOptions: [
      ["Portföy kategorileri", "İlan kategorileri gerçek portföyünüze göre kurulur."],
      ["Danışman profilleri", "Danışman sayısı ve bilgileri ekibinize göre güncellenir."],
      ["Değerleme formu", "Değerleme formu alanları hizmetinize göre düzenlenir."],
      ["Harita entegrasyonu", "Harita, gerçek ilan konumlarınızla senkron çalışır."],
      ["İlan görselleri", "İlan fotoğrafları kendi çekimlerinizle değiştirilir."],
    ],
    keyDecisions: decisions([
      "Hero, öne çıkan bir ilan görseli ve net CTA ile açılır.",
      "Portföy ve değerleme bağlantıları menüde her zaman erişilebilir kalır.",
      "İlan fotoğrafları temiz, aydınlık bir tonda tutarlı sunulur.",
      "İlan kartları eşit hizada, filtre hissi veren bir düzende durur.",
      "Emlak mavisi vurgu, beyaz zeminde net ve güven verici kullanılır.",
      "Mobilde ilanlar tek kolona iner, değerleme CTA'sı görünür kalır.",
    ]),
  }),

  "EML-02": dna({
    styleName: "Lüks villa editoryali",
    accent: "#2F6F9F",
    palette: palette(["Santorini white", "#fffdf8"], ["Aegean blue", "#2f6f9f"], ["Warm sand", "#e8d4b8"], ["Ink", "#171717"], ["Stone", "#c8c0b6"]),
    typographyStyle: "Serif hissi veren editorial başlıklar ve çok sade emlak metinleri.",
    visualDirection: "Villa/lüks konaklama referansından gelen büyük fotoğraf, az metin ve seçkin atmosfer.",
    uiCharacteristics: ["Tam genişlik mimari fotoğraflar", "Minimal CTA", "Sade özellik listeleri", "Clutter-free navigasyon"],
    layoutCharacteristics: ["Görsel hero", "Mülk hikayesi", "Galeri akışı", "İletişim/değerleme kapanışı"],
    interactionStyle: "Fotoğraf ve mimari atmosferi öne çıkaran düşük hareketli deneyim.",
    mobileCharacteristics: ["Büyük görseller kontrollü kırpılır", "Metinler kısa kalır", "CTA sadeleşir", "Galeri dikey akar"],
    sectorFeatures: [
      ["Portföy hikayesi", "Her mülk kısa, editorial bir hikayeyle anlatılır."],
      ["Lüks mülk sunumu", "Mülkler büyük, tam genişlik fotoğraflarla sunulur."],
      ["Danışman iletişimi", "Danışman bilgisi sade bir iletişim bloğunda durur."],
      ["Değerleme veya randevu talebi", "Tek sade CTA ile değerleme veya randevu talebi alınır."],
    ],
    suitableFor: [
      ["Lüks emlak danışmanları", "Seçkin, az sayıda portföyle çalışan danışmanlar."],
      ["Villa satış ekipleri", "Villa ve yazlık portföyü yöneten ekipler."],
      ["Butik gayrimenkul markaları", "Editorial bir marka dili arayan gayrimenkul markaları."],
      ["Az sayıda seçkin portföyü olan ofisler", "Nicelikten çok niteliği öne çıkaran ofisler."],
    ],
    customizationOptions: [
      ["Portföy görselleri", "Mimari fotoğraflar kendi mülk çekimlerinizle değişir."],
      ["Mülk detayları", "Özellik listeleri gerçek mülk bilgilerinize göre kurulur."],
      ["Danışman alanı", "Danışman bilgisi ve iletişim kanalı güncellenir."],
      ["Tipografik ton", "Başlık karakteri markanızın diline göre ayarlanır."],
      ["İletişim formu", "İletişim formu kullandığınız kanala bağlanır."],
    ],
    keyDecisions: decisions([
      "Hero, tam genişlik bir mimari fotoğrafla sade bir başlık taşır.",
      "Navigasyon neredeyse görünmez kalır, tek minimal CTA öne çıkar.",
      "Büyük mimari fotoğraflar az metinle, geniş boşlukla sunulur.",
      "Mülk hikayesi ve galeri arasında sade, editorial bir akış kurulur.",
      "Ege mavisi vurgu, sıcak beyaz zeminde ölçülü kullanılır.",
      "Mobilde görseller kontrollü kırpılır, metinler kısa kalır.",
    ]),
  }),

  "EML-03": dna({
    styleName: "Koyu lüks gayrimenkul",
    accent: "#A9873F",
    palette: palette(["Forest black", "#07110c"], ["Moss", "#536b45"], ["Gold", "#c9a15d"], ["Ivory", "#f5efe2"], ["Deep green", "#163022"]),
    typographyStyle: "Lüks konut algısı veren büyük, sakin ve koyu tema uyumlu başlıklar.",
    visualDirection: "Moody mimari/doğa fotoğrafı, lüks villa hissi ve zengin portföy sunumu.",
    uiCharacteristics: ["Koyu portföy kartları", "Premium CTA'lar", "Mimari fotoğraf ağırlığı", "Blog/servis blokları"],
    layoutCharacteristics: ["Atmosferik hero", "Properties ve servisler", "Yorum/güven akışı", "İletişim kapanışı"],
    interactionStyle: "Premium algıyı destekleyen ölçülü hover ve görsel odaklı geçişler.",
    mobileCharacteristics: ["Koyu kontrast korunur", "Portföy kartları tek kolon", "CTA netleşir", "Fotoğraflar dikey vurgulanır"],
    sectorFeatures: [
      ["Lüks portföy sunumu", "Portföy koyu, atmosferik fotoğraflarla vitrine çıkarılır."],
      ["Danışmanlık hizmetleri", "Danışmanlık hizmetleri kısa, premium bir dille anlatılır."],
      ["Blog/içgörü alanı", "Piyasa içgörüleri ayrı bir bilgi bloğunda sunulur."],
      ["Değerleme talebi", "Tek premium CTA ile değerleme talebi alınır."],
    ],
    suitableFor: [
      ["Lüks emlak ofisleri", "Üst segment portföyle çalışan ofisler."],
      ["Villa ve arsa proje satış ekipleri", "Proje bazlı lüks satış yürüten ekipler."],
      ["Yatırım odaklı danışmanlar", "Yatırımcıya hitap eden danışmanlar."],
      ["Premium gayrimenkul markaları", "Koyu, cesur bir kimlik arayan gayrimenkul markaları."],
    ],
    customizationOptions: [
      ["Portföy kategori yapısı", "Portföy kategorileri gerçek envanterinize göre kurulur."],
      ["Koyu tema tonu", "Zemin koyuluğu ve yeşil tonu markanıza göre ayarlanır."],
      ["Vurgu rengi", "Altın vurgu farklı bir premium tonla değiştirilebilir."],
      ["Danışman profilleri", "Danışman bilgileri ekibinize göre güncellenir."],
      ["Harita/değerleme akışı", "Harita ve değerleme formu gerçek verilerinize bağlanır."],
    ],
    keyDecisions: decisions([
      "Moody, atmosferik bir mimari fotoğrafla koyu hero açılır.",
      "Menü sade kalır, premium CTA koyu zeminde net görünür.",
      "Mimari ve doğa fotoğrafları ağırlıklı, sakin bir ton kurulur.",
      "Portföy kartları koyu zeminde net sınırlarla ayrılır.",
      "Altın vurgu, orman yeşili zeminde seçici kullanılır.",
      "Mobilde koyu kontrast korunur, portföy kartları tek kolona iner.",
    ]),
  }),

  "OTO-01": dna({
    styleName: "Modern oto servis dönüşüm sayfası",
    accent: "#DC2626",
    palette: palette(["Service white", "#ffffff"], ["Signal red", "#ef4444"], ["Steel blue", "#334155"], ["Light gray", "#f1f5f9"], ["Black", "#111827"]),
    typographyStyle: "Güçlü ve pratik servis hissi veren modern sans-serif başlıklar.",
    visualDirection: "Oto servis, fiyat, süreç ve randevu akışını net şekilde anlatan conversion yapısı.",
    uiCharacteristics: ["Servis kartları", "Fiyat/paket blokları", "Süreç adımları", "Randevu CTA'ları"],
    layoutCharacteristics: ["Hero sonrası hizmetler", "Paket ve süreç", "FAQ ve güven", "Randevu kapanışı"],
    interactionStyle: "Hızlı servis randevusu ve net aksiyonlara yönlendiren pratik etkileşimler.",
    mobileCharacteristics: ["Servisler tek kolon", "Paketler kısa kartlarda", "Randevu CTA'sı belirgin", "Süreç adımları numaralı akar"],
    sectorFeatures: [
      ["Servis randevusu", "Hizmet seçilerek tek ekranda servis randevusu alınır."],
      ["Hizmet paketleri", "Bakım paketleri fiyatlarıyla karşılaştırmalı sunulur."],
      ["Araç teslim süreci", "Teslim süreci numaralı adımlarla anlatılır."],
      ["Konum ve yol tarifi", "Servis adresi ve yol tarifi iletişim bölümünde durur."],
    ],
    suitableFor: [
      ["Oto servisleri", "Randevu ve fiyatı net anlatmak isteyen servisler."],
      ["Tamir bakım işletmeleri", "Hizmet çeşitliliğini kart halinde sunmak isteyenler."],
      ["Lastik ve bakım merkezleri", "Paket bazlı çalışan bakım merkezleri."],
      ["Çok hizmetli garajlar", "Farklı hizmetleri tek sayfada toplayan garajlar."],
    ],
    customizationOptions: [
      ["Servis listesi", "Hizmet listesi kendi servis menünüze göre kurulur."],
      ["Paket fiyatları", "Paket fiyatları güncel tarifenize göre güncellenir."],
      ["Randevu akışı", "Randevu formu kullandığınız sisteme bağlanır."],
      ["Konum bilgisi", "Adres ve harita gerçek şube konumunuza göre ayarlanır."],
      ["Araç teslim süreci", "Teslim adımları kendi iş akışınıza göre yeniden yazılır."],
    ],
    keyDecisions: decisions([
      "Hero, net bir hizmet vaadi ve güçlü randevu CTA'sıyla açılır.",
      "Randevu bağlantısı üstte sabit kalır, menü pratik tutulur.",
      "Servis ve araç fotoğrafları net, güven verici bir tonda sunulur.",
      "Hizmet kartları eşit hizada, paket bilgisi kısa tutulur.",
      "Sinyal kırmızısı vurgu, beyaz zeminde CTA'ları öne çıkarır.",
      "Mobilde servisler tek kolona iner, süreç adımları numaralı akar.",
    ]),
  }),

  "OTO-02": dna({
    styleName: "Minimal stüdyo tarzı otomotiv uyarlaması",
    accent: "#475569",
    palette: palette(["Studio white", "#fbfbfb"], ["Black", "#0f0f0f"], ["Concrete", "#d6d3d1"], ["Muted blue", "#62748e"], ["Silver", "#e7e5e4"]),
    typographyStyle: "Swiss/editorial hissi olan büyük sans-serif başlıklar ve çok sade metin ritmi.",
    visualDirection: "Otomotiv için birebir değil; minimal, stüdyo kalitesinde marka sunumu referansı.",
    uiCharacteristics: ["Az renkli yüzeyler", "Büyük tipografi", "Portfolyo benzeri iş sunumu", "İnce çizgili CTA'lar"],
    layoutCharacteristics: ["Minimal hero", "Seçilmiş hizmet/proje blokları", "Süreç anlatımı", "İletişim kapanışı"],
    interactionStyle: "Sakin, ajans/stüdyo kalitesinde ve içerik odaklı geçişler.",
    mobileCharacteristics: ["Başlıklar kısa kırılır", "Kart sayısı sınırlı kalır", "Görseller temiz akar", "CTA gürültüsüzdür"],
    sectorFeatures: [
      ["Premium bakım hizmetleri", "Seçilmiş hizmetler sade, portfolyo benzeri kartlarda sunulur."],
      ["İşçilik portföyü", "Tamamlanan işler stüdyo kalitesinde görsellerle sergilenir."],
      ["Süreç ve teslim anlatımı", "Süreç kısa, sade adımlarla anlatılır."],
      ["Randevu talebi", "Tek ince bir CTA ile randevu talebi alınır."],
    ],
    suitableFor: [
      ["Detailing stüdyoları", "Görsel kaliteyi öne çıkarmak isteyen stüdyolar."],
      ["Premium oto bakım markaları", "Minimal, stüdyo kalitesinde konumlanan markalar."],
      ["Az hizmetli butik garajlar", "Az ama seçkin hizmet sunan garajlar."],
      ["Görsel portföyü güçlü işletmeler", "Elinde güçlü iş görselleri olan işletmeler."],
    ],
    customizationOptions: [
      ["Otomotiv görselleri", "İş görselleri kendi portföy çekimlerinizle değişir."],
      ["Hizmet seçkisi", "Sunulan hizmet sayısı ve türü işletmenize göre kurulur."],
      ["Portfolyo/proje alanı", "Proje kartları gerçek işlerinizle güncellenir."],
      ["Renk nötrlüğü", "Nötr palet farklı bir sakin tonla değiştirilebilir."],
      ["İletişim formu", "İletişim formu kullandığınız kanala bağlanır."],
    ],
    keyDecisions: decisions([
      "Minimal hero, tek büyük başlık ve az renkle açılır.",
      "Navigasyon ince çizgili, tek sakin CTA öne çıkar.",
      "İş görselleri stüdyo kalitesinde, az renkli yüzeylerde sunulur.",
      "Proje kartları sınırlı sayıda, geniş boşlukla ayrılır.",
      "Mat mavi vurgu, beton tonu zeminde düşük yoğunlukla durur.",
      "Mobilde başlıklar kısa kırılır, kart sayısı sınırlı kalır.",
    ]),
  }),

  "OTO-03": dna({
    styleName: "Koyu premium body shop",
    accent: "#B91C1C",
    palette: palette(["Garage black", "#08090b"], ["Racing red", "#dc2626"], ["Carbon", "#1f2937"], ["Chrome", "#d1d5db"], ["Amber", "#f59e0b"]),
    typographyStyle: "Yüksek enerjili, koyu tema üzerinde güçlü oto servis tipografisi.",
    visualDirection: "Koyu, performans odaklı, body shop/detailing ve güven puanlarıyla destekli.",
    uiCharacteristics: ["Koyu hizmet kartları", "Kırmızı CTA'lar", "Puan/yorum göstergeleri", "CMS servis/news alanları"],
    layoutCharacteristics: ["Dramatik hero", "Servis ve haber blokları", "Güven puanı", "Randevu kapanışı"],
    interactionStyle: "Enerjik hoverlar, hızlı aksiyonlar ve performans hissi veren vurgu kullanımı.",
    mobileCharacteristics: ["Koyu kontrast güçlü", "Servisler kısa bloklarda", "Randevu CTA'sı sabit zihinde kalır", "Görseller agresif kırpılır"],
    sectorFeatures: [
      ["Body shop hizmetleri", "Hizmetler koyu, performans hissi veren kartlarda sunulur."],
      ["Detailing/tuning paketleri", "Paketler kırmızı vurgulu kartlarla karşılaştırılır."],
      ["Müşteri yorumları", "Puan ve yorumlar güven göstergesi olarak öne çıkar."],
      ["Servis randevusu", "Tek net CTA ile koyu temada randevu alınır."],
    ],
    suitableFor: [
      ["Premium oto servisleri", "Performans odaklı, üst segment servisler."],
      ["Detailing merkezleri", "Görsel etkiyi öne çıkarmak isteyen merkezler."],
      ["Body shop işletmeleri", "Enerjik, cesur bir kimlik arayan işletmeler."],
      ["Performans/tuning garajları", "Tutkulu, performans odaklı bir müşteri kitlesine hitap edenler."],
    ],
    customizationOptions: [
      ["Servis kategorileri", "Hizmet listesi gerçek servis menünüze göre kurulur."],
      ["Kırmızı/vurgu tonu", "Vurgu rengi kırmızı dışında da seçilebilir."],
      ["Araç görselleri", "Araç fotoğrafları kendi iş görselleriniz olur."],
      ["Yorum/puan alanı", "Puan ve yorumlar gerçek müşteri geri bildirimleriyle doldurulur."],
      ["Randevu ve konum akışı", "Randevu ve konum bilgisi gerçek şubenize bağlanır."],
    ],
    keyDecisions: decisions([
      "Dramatik, koyu bir hero güçlü bir performans vaadiyle açılır.",
      "Kırmızı CTA koyu menüde her zaman net görünür kalır.",
      "Araç görselleri agresif kırpımla, yüksek etkili sunulur.",
      "Servis ve haber blokları koyu kartlarla net ayrılır.",
      "Yarış kırmızısı vurgu, karbon zeminde güçlü şekilde kullanılır.",
      "Mobilde koyu kontrast korunur, randevu CTA'sı sabit kalır.",
    ]),
  }),

  "MIM-01": dna({
    styleName: "Modern renovation ve inşaat akışı",
    accent: "#A16207",
    palette: palette(["Builder white", "#ffffff"], ["Construction yellow", "#facc15"], ["Graphite", "#1f2937"], ["Concrete", "#e5e7eb"], ["Warm wood", "#9a6b3f"]),
    typographyStyle: "Net, güven veren ve dönüşüm odaklı inşaat/renovasyon tipografisi.",
    visualDirection: "Servis, süreç, FAQ ve iletişim hunisi güçlü, açıklayıcı inşaat referansı.",
    uiCharacteristics: ["Hizmet kartları", "Süreç adımları", "Güçlü CTA hunisi", "FAQ ve güven alanları"],
    layoutCharacteristics: ["Hero sonrası hizmetler", "Çalışma süreci", "Proje/kanıt blokları", "Contact kapanışı"],
    interactionStyle: "Teklif veya keşif talebine yönlendiren, net ve düşük sürtünmeli etkileşimler.",
    mobileCharacteristics: ["Süreç adımları numaralı akar", "Hizmet kartları kısa", "Keşif CTA'sı belirgin", "Uzun içerikler bölümlenir"],
    sectorFeatures: [
      ["Proje portföyü", "Tamamlanan projeler önce/sonra görselleriyle sunulur."],
      ["Hizmet alanları", "Hizmet başlıkları net, kısa kartlarla listelenir."],
      ["Süreç anlatımı", "Keşiften teslime süreç numaralı adımlarla anlatılır."],
      ["Keşif talebi", "Proje bilgisi girilerek tek adımda keşif talebi alınır."],
    ],
    suitableFor: [
      ["Renovasyon firmaları", "Süreci net anlatmak isteyen renovasyon firmaları."],
      ["İnşaat şirketleri", "Proje portföyünü güven verici sunmak isteyen şirketler."],
      ["Tadilat ekipleri", "Küçük-orta ölçekli tadilat işleri yürüten ekipler."],
      ["Proje bazlı hizmet veren firmalar", "Her projeyi ayrı vaka olarak anlatmak isteyenler."],
    ],
    customizationOptions: [
      ["Hizmet alanları", "Hizmet listesi gerçek uzmanlık alanlarınıza göre kurulur."],
      ["Proje görselleri", "Proje fotoğrafları kendi işlerinizle değiştirilir."],
      ["Süreç adımları", "Süreç adımları kendi iş akışınıza göre yeniden yazılır."],
      ["Keşif formu", "Keşif formu alanları hizmetinize göre düzenlenir."],
      ["Güven belgeleri", "Belge/referans alanı sertifikalarınıza göre doldurulur."],
    ],
    keyDecisions: decisions([
      "Hero, tamamlanmış bir proje görseli ve net keşif CTA'sıyla açılır.",
      "Keşif talebi bağlantısı menüde sabit kalır, huni net tutulur.",
      "Proje fotoğrafları önce/sonra karşılaştırmasıyla güven kurar.",
      "Hizmet ve süreç blokları numaralı adımlarla net ayrılır.",
      "İnşaat sarısı vurgu, beyaz zeminde dikkatle sınırlı kullanılır.",
      "Mobilde süreç adımları numaralı akar, keşif CTA'sı belirgin kalır.",
    ]),
  }),

  "MIM-02": dna({
    styleName: "Sade mimarlık/interior editoryali",
    accent: "#6B6355",
    palette: palette(["Gallery white", "#fafaf8"], ["Black", "#111111"], ["Stone", "#c9c3b8"], ["Warm gray", "#e7e2da"], ["Muted olive", "#6f735f"]),
    typographyStyle: "Mimarlık stüdyosu hissi veren rafine, sade ve proje odaklı tipografi.",
    visualDirection: "Az öğeli, seçilmiş projeleri ve stüdyo tavrını öne çıkaran editorial yapı.",
    uiCharacteristics: ["Büyük proje görselleri", "Minimal navigasyon", "İnce metin blokları", "Sade proje listeleri"],
    layoutCharacteristics: ["Project-first hero", "Stüdyo anlatımı", "Seçilmiş işler", "İletişim kapanışı"],
    interactionStyle: "Galeri benzeri sakin geçişler ve projeyi öne çıkaran düşük hareket.",
    mobileCharacteristics: ["Projeler dikey galeriye dönüşür", "Metinler kısa tutulur", "Boşluk ritmi korunur", "CTA minimaldir"],
    sectorFeatures: [
      ["Proje portföyü", "Seçilmiş projeler büyük, sade görsellerle sunulur."],
      ["Stüdyo/hizmet anlatımı", "Stüdyo yaklaşımı kısa bir editorial metinle anlatılır."],
      ["Referans proje detayları", "Her proje kısa bir açıklama satırıyla desteklenir."],
      ["İletişim/keşif talebi", "Tek minimal CTA ile iletişim veya keşif talebi alınır."],
    ],
    suitableFor: [
      ["Mimarlık ofisleri", "Projelerini sade bir galeride sunmak isteyen ofisler."],
      ["İç mimarlık stüdyoları", "Editorial bir marka dili arayan stüdyolar."],
      ["Dekorasyon markaları", "Görsel kaliteyi öne çıkarmak isteyen markalar."],
      ["Az ama güçlü portföyü olan ekipler", "Nicelikten çok niteliği önceliklendiren ekipler."],
    ],
    customizationOptions: [
      ["Proje kategorileri", "Proje kategorileri kendi çalışma alanlarınıza göre kurulur."],
      ["Stüdyo metni", "Stüdyo anlatım metni kendi hikayenizle değiştirilir."],
      ["Görsel seçimi", "Proje görselleri kendi çekimlerinizle güncellenir."],
      ["Tipografik ton", "Başlık karakteri stüdyo kimliğinize göre ayarlanır."],
      ["İletişim akışı", "İletişim formu kullandığınız kanala bağlanır."],
    ],
    keyDecisions: decisions([
      "Project-first hero, tek büyük proje görseliyle açılır.",
      "Navigasyon minimalde kalır, tek sade CTA öne çıkar.",
      "Proje görselleri büyük ve az sayıda, geniş boşlukla sunulur.",
      "Proje listesi ince metin bloklarıyla sade şekilde ayrılır.",
      "Zeytin tonu vurgu, galeri beyazında çok düşük kontrastla durur.",
      "Mobilde projeler dikey bir galeriye dönüşür, metinler kısa kalır.",
    ]),
  }),

  "MIM-03": dna({
    styleName: "Koyu premium architecture studio",
    accent: "#A8823F",
    palette: palette(["Studio black", "#080807"], ["Warm gold", "#c9a66b"], ["Deep brown", "#241a12"], ["Ivory", "#f7efe3"], ["Charcoal", "#27272a"]),
    typographyStyle: "Architecture studio algısı veren büyük, sakin ve koyu tema uyumlu editorial başlıklar.",
    visualDirection: "Koyu, altın vurgulu, moody mimari fotoğraflar ve stüdyo metodolojisi.",
    uiCharacteristics: ["Koyu proje kartları", "Altın vurgu çizgileri", "Basın/metodoloji alanları", "Premium CTA"],
    layoutCharacteristics: ["Moody hero", "Proje vitrini", "Stüdyo yöntemi", "Basın ve iletişim kapanışı"],
    interactionStyle: "Premium stüdyo hissini koruyan ölçülü geçişler ve görsel odaklı hoverlar.",
    mobileCharacteristics: ["Koyu kontrast korunur", "Proje kartları tek kolon", "Metodoloji kısa adımlara ayrılır", "CTA net kalır"],
    sectorFeatures: [
      ["Proje portföyü", "Projeler koyu zeminde büyük, moody görsellerle sunulur."],
      ["Metodoloji anlatımı", "Çalışma yöntemi kısa, numaralı adımlarla anlatılır."],
      ["Basın/referans alanı", "Basın ve referanslar ayrı bir güven bloğunda sıralanır."],
      ["Keşif talebi", "Tek premium CTA ile keşif talebi alınır."],
    ],
    suitableFor: [
      ["Premium mimarlık ofisleri", "Üst segment, cesur bir kimlik arayan ofisler."],
      ["İç mimarlık stüdyoları", "Moody, atmosferik bir sunum isteyen stüdyolar."],
      ["Dekorasyon ve konsept ekipleri", "Konsept çalışmalarını öne çıkaran ekipler."],
      ["High-end inşaat markaları", "Lüks segmentte konumlanan inşaat markaları."],
    ],
    customizationOptions: [
      ["Proje görselleri", "Proje fotoğrafları kendi çekimlerinizle değişir."],
      ["Altın/vurgu tonu", "Vurgu rengi altın dışında da seçilebilir."],
      ["Metodoloji adımları", "Çalışma yöntemi kendi sürecinize göre yeniden yazılır."],
      ["Basın/referans alanı", "Basın ve referans listesi güncel içeriklerinizle doldurulur."],
      ["Keşif formu", "Keşif formu alanları hizmetinize göre düzenlenir."],
    ],
    keyDecisions: decisions([
      "Moody bir hero, koyu zeminde tek etkileyici proje görseliyle açılır.",
      "Menü sade kalır, premium CTA koyu temada net görünür.",
      "Mimari fotoğraflar düşük anahtarlı ışıkla stüdyo hissi kurar.",
      "Proje kartları koyu zeminde altın çizgilerle net ayrılır.",
      "Sıcak altın vurgu, neredeyse siyah zeminde seçici kullanılır.",
      "Mobilde koyu kontrast korunur, proje kartları tek kolona iner.",
    ]),
  }),
};
